- faucet.yaml-dist
*sigh*
Make the code public, open the first file and the first thing you see is an error.
I was testing catching syntax errors in the config and somehow that made it into the commit
> Trivial error in faucet.yaml-dist

- faucet.py
And simplify logic in port status handler.
> Fix signal handler (use event framework)

- dp.py
- valve.py
Following config applies an input ACL to port 1.
Supports any ACL rule that https://github.com/osrg/ryu/blob/master/ryu/lib/ofctl_v1_3.py to_match() supports.
1:
native_vlan: 2040
acl_in: 1
vlans:
2040:
name: "dev VLAN"
acls:
1:
- rule:
nw_dst: "172.0.0.0/8"
dl_type: 0x800
allow: 1
- rule:
dl_type: 0x0806
allow: 1
- rule:
nw_dst: "10.0.0.0/16"
dl_type: 0x800
allow: 0
- rule:
> Add ACL support.

- tests/faucet_mininet_test.py
* Wait for switches to connect before trying to pass traffic.
> * Refactor using unittest library.

- tests/faucet_mininet_test.py
Fix tmpdir.
Fix host names to be tagged/untagged.
> Implement mirror test.

- README.rst
Added instructions for testing before issuing a pull-request
> Updated README.rst to include testing information

- .travis.yml
Start of continuous integration testing.  Every time, someone does a commit to the repo, a test is run.  Check out the build history: https://travis-ci.org/onfsdn/faucet/builds.
> Added .travis.yml for continuous integration testing.

- src/ryu_faucet/org/onfsdn/faucet/faucet.py
- src/ryu_faucet/org/onfsdn/faucet/valve.py
- tests/faucet_mininet_test.py
vlans:
100:
description: "untagged"
ip: "10.0.0.254/24"
routes:
- route:
ip_dst: "10.0.1.0/24"
ip_gw: "10.0.0.1"
- route:
ip_dst: "10.0.2.0/24"
ip_gw: "10.0.0.2"
> Implement IPv4 static routes for untagged VLANs.

- src/ryu_faucet/org/onfsdn/faucet/valve.py
* Some lint fixes (line too long)
* Move to consistant quoting (use single quote)
> * Refactor ND and ARP generation into helpers.

- README.rst
- src/ryu_faucet/org/onfsdn/faucet/gauge.py
Fixes gauge logging and logging documentation
Fixes indent bug causing a crash when a datapath leaves
Fixes a typo bug when not using influxdb
> Some gauge bug fixes and documentation updates

- setup.py
I'm not sure if this is the only place I need to update this?
I have no idea how pip packaging works, but this looked as good a place as any :)
> Add dependancy on ipaddr

- docker/Dockerfile
- docker/Dockerfile.gauge
- docker/README.md
- docker/gauge.conf
- docker/supervisord.gauge.conf
Includes a faucet Dockerfile.
And a faucet, gauge, influx and grafana setup in Dockerfile.gauge
> Replaces valve's docker files with faucet ones

- src/ryu_faucet/org/onfsdn/faucet/aruba_pipeline.json
- src/ryu_faucet/org/onfsdn/faucet/aruba_pipeline.py
- src/ryu_faucet/org/onfsdn/faucet/faucet.py
- src/ryu_faucet/org/onfsdn/faucet/ofproto_to_ryu.json
Change adds a few lines to faucet.py to get the handlers registered correctly and 3 new files.
> Added support for Aruba switch custom pipeline configuration

- src/ryu_faucet/org/onfsdn/faucet/aruba_pipeline.py
- src/ryu_faucet/org/onfsdn/faucet/faucet.py
- src/ryu_faucet/org/onfsdn/faucet/valve.py
hardware: Aruba
In FAUCET's config.
> Allow Aruba pipeline to be configured, by specifying:

- MANIFEST.in
- README.rst
- setup.py
- src/cfg/etc/ryu/faucet/gauge.conf
- src/cfg/etc/ryu/faucet/upstart/faucet
- src/cfg/etc/ryu/faucet/upstart/gauge
- src/ryu_faucet/org/onfsdn/faucet/faucet.py
- src/ryu_faucet/org/onfsdn/faucet/gauge.py
Fixes mainly in packaging aspects for production deployment.  Version number bumped to 0.31 too.
> Fixes to enable production deployment.

- src/pkg/bin/run_faucet_in_screen.sh
- src/pkg/bin/run_this_once.sh
These are not included in Python pip distribution
> scripts for VM packaging

- src/docs/faq.rst
- src/ryu_faucet/org/onfsdn/faucet/faucet.py
Re-format the FAQ as ReStructuredText that renders in Github web and edited the language a bit for readability.
> Edit and re-format FAQ for readability

- src/ryu_faucet/org/onfsdn/faucet/dp.py
- src/ryu_faucet/org/onfsdn/faucet/valve.py
- tests/faucet_mininet_test.py
These are the changes associated with the work done at the Hackfest in Sydney (2016). Have tested against existing tests and added two additional tests for new ACL format and ACL mirror.
> Add fine-grained port mirroring and associated tests 

- src/ryu_faucet/org/onfsdn/faucet/dp.py
- src/ryu_faucet/org/onfsdn/faucet/faucet.py
- src/ryu_faucet/org/onfsdn/faucet/valve.py
The table number thing seems to have slipped in accidentally but its a trivial change.
Josh: You will need to test this on an Aruba switch. It is likely that I missed some reference to the ArubaStatelessValve class, but I have no means to test the Aruba code at the moment.
> Inheritance

- tests/faucet_mininet_test.py
Exercise the already-resolved nexthop case for BGP.
> Make helper method to verify presence of a route, flow.

- tests/faucet_mininet_test.py
Lengthen BGP connection/update timeouts.
> Need to start exabgp on IPv6 loopback appropriately.

- Dockerfile.gauge
- README.docker.md
- docker-compose.yaml
- setup.py
- src/ryu_faucet/org/onfsdn/faucet/conf.py
- src/ryu_faucet/org/onfsdn/faucet/config_parser.py
- src/ryu_faucet/org/onfsdn/faucet/db_conf.py
- src/ryu_faucet/org/onfsdn/faucet/dp.py
- src/ryu_faucet/org/onfsdn/faucet/faucet.py
- src/ryu_faucet/org/onfsdn/faucet/gauge.py
- src/ryu_faucet/org/onfsdn/faucet/port.py
- src/ryu_faucet/org/onfsdn/faucet/valve.py
- src/ryu_faucet/org/onfsdn/faucet/vlan.py
- src/ryu_faucet/org/onfsdn/faucet/watcher.py
- src/ryu_faucet/org/onfsdn/faucet/watcher_conf.py
- tests/config/testconfigv2.yaml
- tests/config/testgaugeconfig.conf
- tests/config/testgaugeconfig.yaml
- tests/faucet_mininet_test.py
- tests/test_config.py
Sorrhy I havent split that. If you have an issue with this PR then I'll break it up, but I dont think the other parts are valuable enough on there own to split them into separate branches.
> Config fix

- src/ryu_faucet/org/onfsdn/faucet/dp.py
ipv4_fib_Table --> ipv4_fib_table
> Fix typo in config defaults.

- README.rst
While markup is correct, some features get supported by GitHub when they show up.  Adding the necessary code so that when the rst file gets converted to pdf, the image map for deployment would show up
> trying better variations for embedded URLs and iframe

- tests/faucet_mininet_test.py
* Handle connection errors to ofctl REST API.
* Handle exceptions for multi-DP tests.
> Improvements to exception handling in tests for ofctl REST API.

- src/ryu_faucet/org/onfsdn/faucet/aruba/ovs2json.py
There are 3 updates to the ovs2json.py script in this commit:
1. Handle the condition when none of the flows in a given table
specify match criteria. In this case, we'll need to specify
at least one wildcard to make sure that the table is a TCAM.
2. Print JSON tables in numerically-sorted order.
3. Print JSON in pretty-print format, rather than condensed format.
This will make differences in the output easier to view when
one version is compared with another.
> Update ovs2json.py to handle table with no match specified

- README.docker.md
- README.rst
Add docker instructions to README.rst.
> Docker README.rst updates

- tests/faucet_mininet_test.py
* MultiDP tests added old style v1 gauge parameters which are ignored (removed)
* MultiDP tests should describe inter switch link ports.
> MultiDP test cleanups.

- README.rst
Very small edits to fix wording and expand a couple of acronyms for ease of reading for newer readers
> Minor changes to readme in 'working with real hardware' section

- src/ryu_faucet/org/onfsdn/faucet/aruba/aruba_pipeline.json
I have updated the aruba_pipeline.json file to match the new pipeline of FAUCET based on the TABLE_MATCH_TYPES of each of the table.
> Update the Aruba pipeline to match that of FAUCET

- src/ryu_faucet/org/onfsdn/faucet/valve.py
- tests/test_config.py
Fix some typos and test_config error.
> Incr reload config

- src/pkg/OpenSUSE/misc_tools/restart_faucet.sh
- src/pkg/OpenSUSE/misc_tools/restart_gauge.sh
- src/pkg/OpenSUSE/misc_tools/run_faucet_in_screen.sh
- src/pkg/OpenSUSE/misc_tools/run_gauge_in_screen.sh
- src/pkg/OpenSUSE/misc_tools/run_this_once.sh
code cleanup by removing unused and unnecessary items
> updating scripts

- README.rst
Updated the HPE section of the README file to include links to product lines.
> Update HPE related info in README

- tests/faucet_mininet_test.py
- tests/faucet_mininet_test_base.py
Try harder to confirm hosts learned.
> Reduce parallelism further.

- setup.py
- setup_apps.py
- tests/faucet_mininet_test.py
> We depend on ryu newer than v4.9 for routing.

- requirements.txt
- tests/faucet_mininet_test.py
> Fix testcase for LLDP. Add testcase for CDP.

- src/ryu_faucet/org/onfsdn/faucet/dp.py
- src/ryu_faucet/org/onfsdn/faucet/valve.py
> Make all our default drop rules for certain traffic configurable.

- README.rst
I've tidied a few of the sections to make them easier to read and updated some old information.
Have converted all links to a nicer format too.
> Readme tidy

- src/ryu_faucet/org/onfsdn/faucet/valve_route.py
Simply nexthop cache handling slightly.
> Fix missed check for resolved IP gateway.

- src/ryu_faucet/org/onfsdn/faucet/valve.py
- tests/faucet_mininet_test.py
- tests/faucet_mininet_test_base.py
Group table support causes some errors, will be fixed next change.
> Verify that no OFPErrorMsgs in debug log.

- .gitignore
- setup.py
> Correct list contact.

- README.rst
- docs/vendors/allied-telesis/README_Allied_Telesis.rst
This commit will add Allied Telesis OpenFlow products that support the
Faucet Pipeline
> Add Allied Telesis to the vendors list

- faucet/config_parser.py
Users can config port using vlan vid or vlan name. When loading config, port's vlan reference will be converted to vlan vid.
> a fix for config_parser to check the correctness of vlan reference under port config 

- faucet/valve.py
- tests/faucet_mininet_test.py
> a fix for permanent learning port fails to learn when reloading config

- Dockerfile.tests
- tests/faucet_mininet_test.py
https://github.com/mininet/mininet/wiki/Mininet-2.2.2-Release-Notes
> Update to mininet 2.2.2 (need fix for iperf race condition)

- faucet/dp.py
- faucet/faucet.py
- faucet/valve.py
- faucet/valve_route.py
- tests/faucet_mininet_test.py
RAs with prefix should use network address.
> Make advertise_interval configurable, RAs should use network address in prefix.

- faucet/valve.py
- faucet/valve_packet.py
- faucet/valve_route.py
- tests/faucet_mininet_test.py
If advertise_interval set to 0, disable RAs.
> Set RA A/L flags and verify.

- requirements.txt
Tests passing - https://travis-ci.org/gizmoguy/faucet/builds/239003890
> We rely on at least ryu 4.14.

- faucet/gauge.py
- faucet/watcher.py
Fix more log messages missing DPID.
> watcher.stop() called with erronenous arg.

- faucet/aruba/aruba_pipeline.py
- faucet/tfm_pipeline.py
- faucet/valve.py
- tests/faucet_mininet_test.py
- tests/test_min_pylint.sh
Set DP hardware to "GenericTFM", and configure pipeline in /etc/ryu/faucet/tfm_pipeline.json.
See aruba_pipeline.json for an example.
> Add generic TFM switch support. 

- faucet/faucet.py
- faucet/valve.py
Explicitly hang up on DP if deleted.
> More hangup cases on unknown DPs.

- etc/ryu/faucet/aruba_pipeline.json
- faucet/valve.py
- faucet/valve_route.py
This reverts commit 82d6056ed660c76922b4a7a5af60ca8c1e1570b8.
> Revert "Move arp_tpa to VIP table (less expensive)."

- docs/self_signed_certs.md
Also added instruction of supporting multiple switches.
> Update the paths of keys and certs

- faucet/valve_acl.py
- tests/faucet_mininet_test_unit.py
Example:
- rule:
vlan_vid: 100
actions:
output:
swap_vid: 101
port: acloutport
> Implement vlan_swap action in ACLs.

- Dockerfile.tests
- docker/runtests.sh
Update Dockerfile.tests and runtests.sh to:
- Set env GOPATH;
- Go get the correct gNMI client code;
- Go install the gNMI client;
- Add a gNMI tests placeholder in the runtests.sh
to actually run the client and display help;
> Make the gNMI client run.

- Dockerfile.tests
- docker/runtests.sh
These will be done in gnmi docker instead.
> Clean go imports from testing.

- docker/runtests.sh
- tests/faucet_mininet_test.py
Explicitly call python2 for system tests.
> Even more aggressively schedule workers.

- Dockerfile.gnmi
- gnmi/_startup.sh
- gnmi/run_target.sh
- gnmi/update_gnmi.sh
Add support for updating outdated gNMI sources from running docker image.
> Update gNMI sources.

- Dockerfile.tests
- docker/runtests.sh
- faucet/faucet.py
- faucet/valve.py
- tests/faucet_mininet_test.py
- tests/faucet_mininet_test_base.py
- tests/faucet_mininet_test_unit.py
- tests/faucet_mininet_test_util.py
* OF pcaps automatically parsed.
* Influx tests didn't release temporary port.
* Consistently check for unknown DP when receiving a message.
> Test diagnositics

- Dockerfile
- Dockerfile.gauge
- docker-compose.yaml
- docs/README.docker.md
- etc/prometheus/faucet.rules
- etc/prometheus/prometheus-docker-compose.yml
- faucet/faucet.py
- faucet/gauge_prom.py
- faucet/watcher.py
- faucet/watcher_conf.py
- tests/faucet_mininet_test_base.py
- tests/faucet_mininet_test_unit.py
Add test that gauge prometheus increments byte counters after packets are received.
renames INFLUX_TIMEOUT to DB_TIMEOUT in FaucetTestBase
> Gauge prom

- .travis.yml
- docker/runtests.sh
- tests/test_gauge.py
The gauge unit test is checking the update method in gauge_prom.py
I'm also working to add some more unit tests to add more code coverage to gauge.
> Added a gauge unit test

- faucet/fctl.py
For experimental use to explore requirements (once stable will have output tested).
> Experimental fctl utility for FAUCET/Gauge command line use.

- .travis.yml
- README.rst
- docs/README.docker.md
- docs/README_hw_testing.rst
- docs/README_install.rst
- docs/faq.rst
- docs/vendors/allied-telesis/README_Allied_Telesis.rst
- docs/vendors/hpe/README_Aruba.rst
- gnmi/README.md
Just some updates now that we've moved to our new faucetsdn organisation on github.
> Documentation update

- docs/vendors/allied-telesis/README_Allied_Telesis.rst
FAUCET has been verified to work an AT-X230-10GP.
> Update Allied Telesis vendor documentation: add AT-X230

- faucet/faucet.py
- faucet/gauge.py
Set the environment variable FAUCET_LOG_LEVEL or GAUGE_LOG_LEVEL to the
numeric value of the log level you want:
https://docs.python.org/3/library/logging.html#levels
> Make log level configurable for faucet and gauge.

- setup.cfg
Users can now run FCTL with:
$ fctl --help
> Provide a console script for running FCTL.

- etc/default/faucet
- etc/default/gauge
- etc/logrotate.d/faucet
- etc/logrotate.d/gauge
- etc/systemd/system/faucet.service
- etc/systemd/system/gauge.service
* default environment files for systemd
* systemd unit files
* logrotate configs
> Add some files necessary for packaging faucet.

- vm/.gitignore
- vm/README.md
- vm/build-faucet-vm.sh
- vm/elements/faucet/install.d/02-install-faucet
- vm/elements/faucet/package-installs.yaml
- vm/elements/gauge/install.d/02-install-gauge
- vm/elements/grafana/install.d/02-install-grafana
- vm/elements/prometheus/install.d/02-install-prometheus
- vm/elements/prometheus/install.d/prometheus.service
- vm/elements/prometheus/install.d/prometheus.yml
Adds packaging files for building an all-in-one VM for faucet/gauge/prometheus.
> Add packaging files for our FAUCET VM.

- docker-compose.yaml
* Upgrade influxdb & update environment variables
* Upgrade prometheus
* Upgrade grafana
> Update docker containers used for docker-compose.

- docker-compose.yaml
- docs/README.docker.md
> add FAUCET_PREFIX for specifying paths of volumes

- Dockerfile.tests
- faucet/port.py
- faucet/valve_host.py
- faucet/vlan.py
- tests/faucet_mininet_test_unit.py
If loop_protect: True on a port, learning is temporarily disabled on that port, if hosts rapidly move from other ports to that port.
> Trivial loop protection

- docker-compose-pi.yaml
Note: `couch` was removed, since I couldn't find an image that worked on `armhf`.  Everything else seems to work though, so I'm not sure if that matters for `gauge` or not?
> add compose file for rpi

- docker-compose-pi.yaml
didn't realize they changed when I switched the influxdb image - should work now
> fix environment variables for db and admin user

- docs/README.developerguide.rst
missed adding this when the target was added to the `Makefile`
> add release target to docs

- faucet/dp.py
- tests/test_check_config.py
> Fix referencing an unconfigured ACL #1201

- faucet/config_parser.py
- tests/test_check_config.py
Fix issue #1208 and added some tests.
> Fix #1208, exceptions with funky configs

- faucet/config_parser.py
- tests/test_check_config.py
Fix unhandled exception with invalid strings #1244 and reduced clutter in some test cases.
> Fix issue #1244 and clean up some test cases

- faucet/config_parser.py
- tests/test_check_config.py
Fix unhandled exception with certain fields being empty #1248
> Fix issue #1248; unhandled exceptions with empty fields

- adapters/vendors/rabbitmq/rabbit.py
- faucet/valve_util.py
previous merged PR broke the build, this fixes my mistake
> hotfix changing FAUCET_EVENT_SOCK to a bool

- docs/README.rst
- docs/configuration.rst
- docs/docker.rst
- docs/fuzzing.rst
- docs/installation.rst
- docs/testing.rst
- docs/vendors/allied-telesis/README_Allied_Telesis.rst
- docs/vendors/hpe/README_Aruba.rst
- docs/vendors/lagopus/README_Lagopus.rst
- docs/vendors/northboundnetworks/README_ZodiacFX.rst
- docs/vendors/noviflow/README_noviflow.rst
- docs/vendors/ovs/README_OVS-DPDK.rst
* Clean up code blocks
* Clean up headings
> Tidy documentation.

- docs/conf.py
Napoleon adds support for Google style docstrings to sphinx which are
what we use in faucet.
> Switch to using napoleon for generating code documentation.

- test-requirements.txt
(https://github.com/ahitrin/SiebenApp/commit/ea063d143f140554aaa08606d9c8d58121e8a52c)
> workaround pylint bug.

- faucet/faucet.py
- faucet/faucet_experimental_event.py
- faucet/gauge.py
- faucet/valve_util.py
Fix issue #1416.
Refactor check of event_sock path into separate method.
Remove need for get_bool_setting() api by making get_setting smarter.
> Put default for FAUCET_EVENT_SOCK in get_setting().

- faucet/acl.py
- faucet/config_parser.py
- faucet/config_parser_util.py
- faucet/dp.py
- faucet/valve_acl.py
- faucet/valve_of.py
- faucet/vlan.py
- tests/test_config.py
A lot of the bugs are type errors with acl matching. It's probably better to type check the values in acl.py beforehand.
Also fixes #1413
> Fix unhandled exceptions with bad configs

- faucet/config_parser.py
- tests/test_config_gauge.py
Fix https://github.com/faucetsdn/faucet/issues/1441 and add unit tests for gauge config
> Require dps key

- faucet/config_parser.py
- faucet/config_parser_util.py
- faucet/dp.py
- tests/test_config.py
Fixes:
- #1463 
- #1461 
- #1460 
- #1462
> Handle unhandled exceptions with certain config files.

- faucet/__main__.py
> Add verbose and TLS control channel args to start script.

- docs/docker.rst
> Add documentation for running docker with additional args.

- faucet/__main__.py
> Add optional ryu arguments to startup script.

- docs/vendors/hpe/README_Aruba.rst
Thanks to @abhayb-hpe for the review.
> Updated documentation to include PKI Setup

- faucet/fctl.py
- tests/test_fctl.py
this allows you to only display specific relevant labels when
querying with fctl
> Adds display-labels argument to fctl

- .gitignore
- AUTHORS
- faucet/gauge_influx.py
- faucet/gauge_pollers.py
- faucet/gauge_prom.py
- faucet/watcher.py
- tests/test_gauge.py
Adds unit test for prom port state polling, and adds curr_speed and max_speed fields. Fixes #1544.
> curr_speed and max_speed for prom port state polling

- adapters/vendors/rabbitmq/rabbit.py
- adapters/vendors/rabbitmq/test_rabbit.py
Also added a couple of debug strings.
> rabbitmq adapter use FAUCET_EVENT_SOCK as path.

- faucet/valve.py
> Explicitly decode of_dp_desc_stats labels as UTF8.

- docs/configuration.rst
- faucet/acl.py
Just trying to better document the code that's already there.
> Update output field docs

- tests/faucet_mininet_test_base.py
- tests/faucet_mininet_test_unit.py
Demonstrates ability to apply fine-grain control of both unicast and broadcast traffic.
> Adding stacked ACL reachability test

- Dockerfile.tests
- docker/runtests.sh
- docs/testing.rst
* Fix running test suite in environment with a proxy
* Document how to skip pytype/documentation testing
> Test suite fixes and adding additional documentation.

- .gitlab-ci.yml
- ci/Dockerfile
* Automatically build the dbuilder docker image
* Produce less verbose output
> Tidy gitlab ci.

- docs/configuration.rst
> Document environment variable usage.

- faucet/valve_ryuapp.py
> Log which configuration file we used on startup.

- docker/gasket/Dockerfile.freeradius
Again, ideally this will be using alpine, but haven't been able to get that to work yet. I'll have another crack latter today.
1. What exactly do we want to be able to do with the server?
2. Where should the config files go?
- MD5 is only really supported.
- PEAP/TTLS will not return the Faucet-ACL-ID attribute in Access-Accept messages.
> freeradius 3.0 for gasket

- faucet/valve_of.py
Replaced implementation that uses set arithmetic with a simple
partition function. The set() implementation could change the order of
the original msgs.
Renamed is_delflow to is_delete.
> valve_flowreoder preserves original order within each partition

- faucet/acl.py
- faucet/conf.py
- faucet/config_parser.py
- faucet/dp.py
- faucet/port.py
- faucet/router.py
- faucet/valve_acl.py
- faucet/valve_of.py
- faucet/vlan.py
Replace assert statements with a callable function that raises an InvalidConfigError if the condition parameter is true.
#1839
> Refactor abundance of assert statements

- AUTHORS
> Add Sam Russell to authors

- tests/test_vlan.py
Travis green https://travis-ci.org/samrussell/faucet/builds/377565128
No functional changes, adds new tests for
- VLAN.ipvs()
- VLAN.faucet_vips_by_ipv()
- VLAN.routes_by_ipv()
- VLAN.route_count_by_ipv()
- VLAN.add_route()
- VLAN.del_route()
> Add more VLAN unit tests

- docs/configuration.rst
- faucet/dp.py
- tests/test_dp.py
- tests/test_port.py
- tests/test_vlan.py
Travis green - https://travis-ci.org/samrussell/faucet/builds/377650055
Basic config check for DP, and tests to make sure further changes to __dict__ turn up in to_conf() or a test is added to handle them
> Config test for DP and __dict__ check for DP/port/vlan

- faucet/faucet_experimental_event.py
- tests/test_valve.py
This reverts commit b02c59bd8cf70a980cfa9ab0ebe7a62635089d3e.
> Revert "Test can't remove socket path."

- faucet/faucet_bgp.py
- requirements.txt
- test-requirements.txt
- tests/test_valve.py
> Revert "Swap out Ryu BGPSpeaker for Beka"

- README.rst
- setup.cfg
> Revert "Bump version number."

- faucet/faucet_bgp.py
- requirements.txt
- test-requirements.txt
- tests/test_valve.py
> Swap out Ryu BGPSpeaker for Beka 0.3.1

- tests/test_faucet_bgp.py
Tests with 1x IPv4, 1x IP6 and 1 of each, mocking Beka and counting invocations
> Add FaucetBgp speaker count tests

- requirements.txt
- test-requirements.txt
Refactors, no feature change
https://travis-ci.org/samrussell/faucet/builds/380008007
> Upgrade Beka to 0.3.3

- faucet/valve_acl.py
- faucet/valve_of.py
Refactoring to move OFPActionSetField reference into valve_of.py.
> Add set_field api to valve_of.

- adapters/vendors/rabbitmq/docker-compose-pi.yaml
Add missing docker-compose.yaml for arm support.
> Add rasp pi docker-compose for rabbitmq adaptor.

- faucet/config_parser_util.py
- faucet/valve_util.py
> Exception handling when a file is not found

- clib/mininet_test_base.py
- tests/sysctls_for_tests.sh
Don't set self.net to None on stop.
> Leave TCP config alone.

- docs/configuration.rst
> Document faucet_mac.

- docs/configuration.rst
> Docs tidy.

- .gitlab-ci.yml
- raspbian-image/02-run.sh
- raspbian-image/build.sh
- raspbian-image/common
- raspbian-image/prerun.sh
Gitlab CI faucet raspbian image builder.
I don't know if there is a better way to handle the modified files from RPi-Distro/pi-gen.
https://gitlab.com/mab68/faucet/-/jobs/82184101/artifacts/browse
> Faucet raspbian image with gitlab CI

- faucet/acl.py
- faucet/dp.py
- tests/unit/test_config.py
Fix for https://github.com/faucetsdn/faucet/issues/2058
Also tidies constructor for ACL object to make it more consistent with other conf objects (uses conf __init__ to set valuables and check_config for validation rather than doing it in __init__)
> Acl port resolution

- faucet/acl.py
- faucet/dp.py
> Refactor ACL validation so it is performed by ACL object

- tests/integration/mininet_tests.py
So my idea here is to run `test_fuzz_controller()` tests until they get slow, and then quit.
While this may not completely fix everything, it does enable us to move forward slightly by running more fuzzing tests, and it may also help with debugging the timeout issue.
Note that I do seem to be seeing some controller exceptions with this, such as faucetsdn/faucet#2330
> Try to run as many ICMPv6 fuzz tests as we can

- docker/runtests.sh
This is just a bit of reorganization and cleanup for `runtests.sh` - hopefully it is useful.
- Reduce repeated variable settings and `set -e` so the default behavior is to exit on an error (I am assuming that the specific `exit 1` error code was not important?)
- Add timing (`time ./<test>`) for tests to see how long things are taking
- Also run `pylint` before `pytype` because `pytype` is slow
> Reduce repetition; add timing for tests

- tests/unit/faucet/test_config.py
Slowly working my way through the config tests
> Add tests that config options are generated correctly

- tests/unit/faucet/test_config.py
Continuing to add tests that config options are created correctly
> Validate config objects

- tests/unit/packaging/test_packaging.py
> Add support for pip versions >= 10.

- clib/mininet_test_base.py
- faucet/faucet_dot1x.py
- faucet/faucet_metrics.py
- faucet/valve.py
- tests/integration/mininet_tests.py
Add handlers for failure/logoff - not implemented on chewie side.
Add partial test for logoff - counters not implemented on chewie side.
Add option to connect to wpa_supplicant's control socket.
Also corrected indentation of the last pr.
> Add dp & port metrics for failure/logoff/success.

- faucet/faucet_dot1x.py
- faucet/valve.py
- tests/integration/mininet_tests.py
This reverts commit b252afef7cd55b9c0f47f1cf75054d84a7bb6c65, reversing
changes made to a76f710e1cf0317549307bb56114a8e8cd330fcb.
> Revert "Merge pull request #2377 from Bairdo/chewie-radius"

- clib/mininet_test_base.py
- faucet/valve.py
- faucet/valve_pipeline.py
- faucet/valve_route.py
- faucet/valve_table.py
Obsolesces https://github.com/faucetsdn/faucet/pull/2535
>  Add valve_pipeline class, and goto_this() table method, and pipeline manager handles L3 flows.

- docker-compose-pi.yaml
- docker-compose.yaml
* Update to prometheus v2.4.3
* Upgrade to grafana 5.3.0
> Update images in docker-compose.yaml files.

- faucet/valve.py
- tests/integration/mininet_tests.py
I'd screwed up the ping fail check. Sorry. :(
Will try add a tcpdump check, before i leave shortly or monday.
https://travis-ci.org/Bairdo/faucet/builds/440465340
> 802.1x actually block unauthenticated traffic

- .travis.yml
> Only do travis builds on master and tags.

- .gitlab-ci.yml
* Use latest release of pi-gen rather than master.
* Stage5 no longer exists.
> Fix raspbian builds.

- .travis.yml
> Revert "Only do travis builds on master and tags."

- docs/developer_guide.rst
Initial PR process changes for discussion.
> PR process

- faucet/faucet_dot1x.py
- faucet/valve.py
- tests/integration/mininet_tests.py
previously if the nfv port went down and up, the flows to forward between supplicant and nfv would not be added to the nfv port.
> Correct handling when 802.1X nfv port changes state

- faucet/acl.py
- faucet/conf.py
- faucet/dp.py
- faucet/router.py
- tests/unit/faucet/test_config.py
- Fix #2606 
- Fix #2607 
- Fix #2608 
- Fix #2609
> Fix config parsing errors

- clib/mininet_test_base.py
- faucet/vlan.py
- tests/unit/faucet/test_valve.py
Fixes https://github.com/faucetsdn/faucet/issues/2589.
> Test interfaces could be assigned incorrectly out of order when hardware testing

- faucet/check_faucet_config.py
- tests/unit/faucet/test_check_config.py
Fixes https://github.com/faucetsdn/faucet/issues/2552
> check_faucet_config should print all DPs.

- faucet/gauge.py
- tests/integration/mininet_tests.py
- tests/unit/gauge/test_gauge.py
Fixes https://github.com/faucetsdn/faucet/issues/2612.
> Bootstrap all port state variables when DP connects to Gauge. 

- faucet/watcher_conf.py
- tests/unit/gauge/test_config_gauge.py
Fixes https://github.com/faucetsdn/faucet/issues/2618
> Don't allow all_dps and dps to be set together.

- faucet/watcher_conf.py
- tests/unit/gauge/test_config_gauge.py
Fixes https://github.com/faucetsdn/faucet/issues/2598
> Type check DB parameters for Watchers and check file path is writable.

- faucet/valves_manager.py
- tests/integration/mininet_tests.py
Fixes https://github.com/faucetsdn/faucet/issues/2594
> Send CONFIG_CHANGE success message.

- clib/mininet_test_base.py
- tests/integration/mininet_tests.py
Fixes https://github.com/faucetsdn/faucet/issues/2654
> Fix hardcoded port references in 8021X tests, fix hardware tests where ports not 1-4

- docs/vendors/allied-telesis/README_Allied_Telesis.rst
- Updated Faucet guide with new AW+ version
- Added SNMP and sFlow configurations
> Update Vendor page for AT products

- faucet/faucet_dot1x.py
Remove flow on Authentication Denied
> BUGFIX - Deny Port on 802.1x Failure

- .codecov.yml
* Round delta to nearest number instead of down.
* Don't post comment on PR when coverage doesn't change.
* Allow a delta of 0.5% in coverage before reporting as problem.
> Tweak codecov settings.

- docs/configuration.rst
There is a [PR](https://github.com/faucetsdn/chewie/pull/93) over in chewie for PEAP.
> update supported EAP Types in docs

- faucet/valve.py
- faucet/valve_host.py
- faucet/valve_manager_base.py
- faucet/valve_pipeline.py
builds on https://github.com/faucetsdn/faucet/pull/2541
install flows in response to a port coming up in managers rather than valve.
I suspect this may end up with merge conflicts.. lets see what perspires.
> Manager add port

- docs/conf.py
> Prometheus metrics of type counter now end with _total.

- faucet/valve.py
- faucet/valve_pipeline.py
flow mods to move packets throughout the pipeline should be controlled by the pipeline manager.
travis: https://github.com/KitL/faucet/runs/39694338
> Pipeline goto

- faucet/valve.py
- faucet/valve_manager_base.py
- faucet/valve_pipeline.py
use valve managers for generating delete flowmods
> Pipeline deletion

- docs/configuration.rst
Fixes https://github.com/faucetsdn/faucet/issues/2592
> Update interface mirroring documentation interaction with ACL mirroring.

- tests/integration/mininet_tests.py
> change formatter for ports < 65535

- faucet/valve.py
- faucet/valve_host.py
- faucet/valve_pipeline.py
travis: https://github.com/KitL/faucet/runs/39722049
> Valve pipeline remove filters

- tests/unit/faucet/fakeoftable.py
check flow mods dont have duplicate instructions
> Include unit test to catch faulty instructions

- tests/unit/faucet/test_valve.py
Fixes https://github.com/faucetsdn/faucet/issues/2666
> Explicitly test config content_changed().

- .gitlab-ci.yml
- debian/control
- debian/rules
* Run unit tests on package builds
* Fix lint errors by adding build-depends
closes #2336 
closes #2334
> Improve debian package builds

- clib/mininet_test_base.py
- faucet/valve.py
- tests/integration/mininet_tests.py
Fixes https://github.com/faucetsdn/faucet/issues/2610
> Detect and log remote LACP actor system ID mismatch.

- faucet/acl.py
- faucet/valve.py
- faucet/valve_acl.py
- faucet/valve_pipeline.py
- Add accept to vlan function to pipeline
- Pass ACL instructions using lists rather than individual instructions
> Use pipeline for accept instructions in acls

- .readthedocs.yml
- docs/README.rst
- docs/_static/tutorial/add_tagged_interface
- docs/_static/tutorial/as_ns
- docs/_static/tutorial/cleanup
- docs/_static/tutorial/create_ns
- docs/conf.py
- docs/requirements.txt
- docs/tutorials/acls.rst
- docs/tutorials/nfv_services.rst
- docs/tutorials/routing.rst
- docs/tutorials/vlans.rst
* Add svg2pdfconverter so that SVGs can be rendered in LaTeX
* Misc tutorial cleanups
> Tutorial updates

- faucet/fctl.py
- tests/unit/faucet/test_fctl.py
Fixes https://github.com/faucetsdn/faucet/issues/2710
> ftctl should andle bad URL or content.

- clib/clib_mininet_test_main.py
1. Print test results in YAML format.
2. Print sanity test result even when sanity tests are failed.
3. Involve SKIPPED tests into test results.
> Log print enhancement. 

- faucet/valve.py
- faucet/vlan.py
- tests/integration/mininet_tests.py
- fixed logging
- corrected the handling of lag port down
> lacp improvement

- faucet/fctl.py
- tests/unit/faucet/test_fctl.py
Adds a get_samples method to fctl which can be imported to aid
querying prometheus from code
> Add a method for querying prometheus in code

- faucet/faucet_dot1x.py
- tests/integration/mininet_tests.py
update of PR #2697 works on software but not hardware, see comment https://github.com/faucetsdn/faucet/pull/2697#issuecomment-462489499 for failure messages.
> Fix: 'Bugfix: Chewie port never comes back up'

- docs/architecture.rst
As suggested by https://github.com/faucetsdn/faucet/issues/2797#issuecomment-464518340 remove the "Table NN: " prefixes from each of the table headings (replacing them with "FOO Table") to make the names more prominent than the Table numbers used.
The diagram referenced from `architecture.rst` is also clearly out of date (eg, https://github.com/faucetsdn/faucet/issues/2797#issuecomment-463473745), but it appears to have been generated by some external tool with no source file available, so it is not updated.   Possibly someone with the source file for that diagram could update it, and remove the table ID numbers?
The `faucet-pipeline.png` diagram is at:
https://github.com/faucetsdn/faucet/blob/master/docs/_static/images/faucet-pipeline.png
and there's a `faucet-pipeline.txt` in the same …
> docs/architecture: remove table numbers

- clib/clib_mininet_test_main.py
- docker/runtests.sh
- test-requirements.txt
- tests/fuzzer/display_packet_crash.py
- tests/fuzzer/fuzz_config.py
- tests/fuzzer/fuzz_packet.py
General clean ups to test suite.
> Fix unit tests

- .travis.yml
- clib/mininet_test_base.py
- setup.cfg
- tests/codecheck/pylint.sh
- tests/codecheck/pytype.sh
- tests/integration/mininet_tests.py
- tests/run_unit_tests.sh
- travis/runtests.sh
* Add support for ubuntu 18.04 test-base images
* Add support for freeradius3
* Default to python3.6 for tests
* Run unit tests in parallel (closes #2808)
* Optimize our travis runs (closes #2313)
> Incremental test suite improvements

- .readthedocs.yml
> Migrate .readthedocs.yml to version 2.0 syntax.

- docs/testing.rst
* Recommend --rm so that docker is removed when it finishes running.
* Mount /var/lib/docker so that docker-in-docker keeps working.
> Update docker run documentation for test suite.

- clib/mininet_test_base.py
- faucet/valve.py
- faucet/valves_manager.py
- tests/integration/mininet_tests.py
Also fixes some broken LACP tests 8021X tests for hardware.
> Incremental fix for hardware port mapping - add layer to rewrite faucet.yaml to use the correct ports consistently

- test-requirements.txt
* Upgrade pytype
* Suppress pyup upgrades for scapy
> Test requirements changes

- clib/clib_mininet_test_main.py
- tests/unit/gauge/test_gauge.py
Fixes https://github.com/faucetsdn/faucet/issues/2858
> Should use yaml.safe_load().

- faucet/acl.py
Fixes https://github.com/faucetsdn/faucet/issues/2861
> Remove dl_dst output action from ACLs (which did not work anymore anyway)

- tests/unit/faucet/test_valve.py
Fixes https://github.com/faucetsdn/faucet/issues/2862
> Use relative time comparison profiling config parsing performance.

- docs/installation.rst
- images/vm/build-faucet-vm.sh
requires faucetsdn/docker-dbuilder#1 to be merged
closes #2819
> Upgrade VM image to Ubuntu Bionic

- clib/mininet_test_base.py
- docs/configuration.rst
- docs/tutorials/routing.rst
- faucet/conf.py
- faucet/dp.py
- faucet/faucet_bgp.py
- faucet/router.py
- faucet/vlan.py
- tests/fuzzer/dict/config.dict
- tests/integration/mininet_tests.py
- tests/unit/faucet/test_config.py
- tests/unit/faucet/test_valve.py
- tests/unit/faucet/test_vlan.py
Fixes https://github.com/faucetsdn/faucet/issues/2563
> Move BGP configuration from VLAN to Router.

- .travis.yml
- debian/changelog
- debian/control
- docs/installation.rst
- faucet/__main__.py
- setup.cfg
- setup.py
> Sunset python versions < 3.5

- docs/configuration.rst
- docs/intro.rst
- docs/release_notes/1.7.0.rst
- docs/release_notes/1.9.0.rst
> Faucet 1.9 release notes

- clib/mininet_test_base.py
- debian/control
- faucet/faucet_dot1x.py
- faucet/valve_acl.py
- requirements.txt
- tests/integration/mininet_tests.py
- tests/unit/faucet/test_valve.py
closes #2831 
Builds on top of PR #2856 
Requires https://github.com/faucetsdn/chewie/pull/117
> periodic reauth

- tests/integration/mininet_tests.py
It was checking the order, but that was causing failures when events were received out of the expected order. (e.g. port 3 up after port 1). So this just checks they occur.
> change 802.1x event checks to not check order

- AUTHORS
- docs/configuration.rst
- faucet/dp.py
- faucet/faucet_dot1x.py
- faucet/port.py
- faucet/valve_acl.py
- tests/integration/mininet_tests.py
- tests/unit/faucet/test_valve.py
Add ACL functionality to 802.1x ports
Add mininet tests to ensure functionality
> 802.1x ACLs

- docs/configuration.rst
- faucet/dp.py
- faucet/faucet_dot1x.py
- faucet/port.py
- faucet/valve.py
- faucet/valve_flood.py
- faucet/vlan.py
- tests/integration/mininet_tests.py
- tests/unit/faucet/test_valve.py
closes #2830 
requires https://github.com/faucetsdn/chewie/pull/118
test doesn't quite pass yet, when h1 logs on for second time onto vlan 2222.
> dot1x get native vlan from radius

- clib/mininet_test_util.py
- tests/integration/mininet_tests.py
Not entirely sure if I'm doing the udp port part right. (What is the ports_sock part?)
> extract 8021x base test class. find a free udp port for radius

- docs/_static/grafana-dashboards/faucet_instrumentation.json
> Update variables in Grafana dashboards to match Prometheus variables

- clib/mininet_test_base.py
- tests/integration/mininet_tests.py
> verify_unicast() doesn't handle for possible packet loss.

- .gitignore
- clib/mininet_test_topo.py
- faucet/dp.py
- faucet/faucet_metrics.py
- faucet/fctl.py
- faucet/valve_flood.py
- faucet/valve_host.py
- faucet/valve_ryuapp.py
- faucet/vlan.py
- faucet/watcher.py
- tests/codecheck/min_pylint.sh
- tests/unit/faucet/test_config.py
- tests/unit/faucet/test_valve.py
Next step will involve making some larger functions less complex/fewer variables and conditions. Next step after that will be splitting some very large classes up (e.g. Valve) to other helper classes to manage increasing complexity.
> Increase min pylint to 9.44 (incremental step to 9.5).

- clib/clib_mininet_test_main.py
- clib/clib_mininet_tests.py
- clib/mininet_test_base.py
- clib/mininet_test_topo.py
- tests/integration/mininet_tests.py
This reverts commit 97172b7959f0265f6cb054175ed8b7e4c8bbd54f, reversing
changes made to 1eece991779b483524c826b81b16fa9ec485e67b.
> Revert "Merge pull request #2957 from lantz/random-ports" due to complex breakage

- faucet/config_parser.py
- tests/unit/faucet/test_config.py
Fixes https://github.com/faucetsdn/faucet/issues/2956
> DPIDs cannot be duplicated.

- clib/docker_host.py
Handle read() possibly returning more than ps1.
> Add diagnostics for docker container tests.

- faucet/port.py
- faucet/valve.py
- Fixed redundant logging. Logging now only on state change
TODO:
- src mac address validation through expected mac in config
> Fix LLDP logging

- debian/control
- faucet/faucet_dot1x.py
- faucet/valve.py
- requirements.txt
- tests/unit/faucet/test_valve.py
Remove redirection functions inside Valve and use ACL Manager inside Faucet_Dot1x
Change Faucet / Chewie Interface to use KWARGS
> Change Faucet / Chewie Interface to use KWARGS

- tests/unit/faucet/test_config.py
Correcting documentation errors in #3011 and #3012
> Cleanup incorrect documentation in test cases

- docs/configuration.rst
- faucet/acl.py
- faucet/dp.py
- faucet/faucet_dot1x.py
- faucet/port.py
- faucet/valve_acl.py
- faucet/valve_of.py
- faucet/valve_table.py
- tests/integration/mininet_tests.py
- tests/unit/faucet/test_valve.py
Add Rule to forward DHCP (All IP Packets for now) to NFV Port
Add Integration Test for MAB Using DHClient
> Add MAB to Faucet

- docs/configuration.rst
- faucet/acl.py
- faucet/dp.py
- faucet/faucet_dot1x.py
- faucet/port.py
- faucet/valve_acl.py
- tests/integration/mininet_tests.py
- tests/unit/faucet/test_valve.py
Add User Specifc ACL Defined by RADIUS
Add Test for User-specified ACLs
Add Test for Logout using DynACL
Add Test Users to the Radius Config in Mininet_tests
> Add dynamic ACLs for chewie

- clib/mininet_test_base.py
- tests/integration/mininet_tests.py
Fixes https://github.com/faucetsdn/faucet/issues/2718
...and resulting test flakes.
> Sync OF port counters and iperf results better, and use DHCP req not ping -b for host learning

- faucet/faucet_bgp.py
- faucet/valve.py
- faucet/valve_route.py
- tests/integration/mininet_tests.py
Fixes https://github.com/faucetsdn/faucet/issues/2878.
> FAUCET should ignore BGP routes with nexthops not directly connected.

- tests/integration/mininet_tests.py
With new OVS passes fine under Travis.
> Re-enable FaucetUntaggedMultiConfVlansOutputTest.

- clib/mininet_test_base.py
- tests/integration/mininet_tests.py
Remove a lot of redundant code from 8021X checks, and increase coverage of 8021x Prometheus variables.
> 8021x test cleanup

- tests/integration/mininet_tests.py
Fixes https://github.com/faucetsdn/faucet/issues/3109
> Re-enable ARP fuzzing for scapy 2.4.3.

- faucet/valve.py
> Fix #3150 Unhandled KeyError

- faucet/dp.py
- tests/integration/mininet_tests.py
- tests/unit/faucet/test_config.py
- tests/unit/faucet/test_valve.py
> Make sure routers on each DP have the required VLANs to route

- clib/mininet_test_base.py
- clib/mininet_test_topo.py
This is a variant of an experiment suggested by @gizmoguy I believe.
For FaucetSwitch to work properly, `switch.cmd()` should always succeed, so we check the exit code and raise a `RuntimeError` if it doesn't match the expected value (zero by default.)
To accept any exit code, you can pass in `success=None` or append a  `true` to the
command, e.g. `s1.cmd('some_cmd || true')`.
This should allow us to simplify any result checks for switch commands.
> Add exit code checking to FaucetSwitch.cmd()

- clib/mininet_test_topo.py
minor changes to `mininet_test_topo.py`:
- pylint annotations
- python 3 simplifications
> mininet_test_topo.py changes to make pylint happier

- docs/vendors/hpe/README_Aruba.rst
Remove DNS dependant examples.
Explain requirements for VLAN VIDs.
> Simplify Aruba config doc.

- faucet/config_parser.py
- faucet/gauge.py
- tests/unit/gauge/test_config_gauge.py
- tests/unit/gauge/test_gauge.py
Fixes https://github.com/faucetsdn/faucet/issues/2721
> Gauge can detect and reload when FAUCET's config changes.

- tests/unit/faucet/test_valve_config.py
Fixes https://github.com/faucetsdn/faucet/issues/2447.
> Add test to show mirroring a port is a warm start.

- clib/clib_mininet_test_main.py
- clib/mininet_test_base.py
- faucet/gauge.py
- faucet/gauge_influx.py
- faucet/gauge_pollers.py
- faucet/gauge_prom.py
- faucet/watcher.py
- faucet/watcher_conf.py
- tests/integration/mininet_tests.py
- tests/unit/gauge/test_config_gauge.py
- tests/unit/gauge/test_gauge.py
Prometheus support for meters coming in next PR.
> Enable meter testing and Gauge support for meter stats logging (and Gauge tech debt reduction).

- faucet/valve_flood.py
- tests/unit/faucet/test_valve_stack.py
- tests/unit/faucet/valve_test_lib.py
Provisional fix to NoReflection algorithm that allows a system to operate with calculated-MST flooding. Alternative solution would be to create another flood manager with this behavior. Still needs tests.
> Allow MST flooding from NoReflection algorithm with wounded stack.

- faucet/valve.py
- faucet/valve_flood.py
- tests/run_unit_tests.sh
- tests/unit/faucet/fakeoftable.py
- tests/unit/faucet/test_valve_stack.py
- tests/unit/faucet/valve_test_lib.py
This is a faucet-functionality-neutral update to the tests in advance of some other work I'm doing. I figured out I was going to need to update the tests some, so wanted to do that in a separate functionality-neutral PR.
> Update unit tests to support hairpin and table counts

- docs/vendors/hpe/README_Aruba.rst
For reference, please check currently generated section https://docs.faucet.nz/en/latest/vendors/hpe/README_Aruba.html#switch
> Fixed markup so that docs are generated correctly

- faucet/router.py
- tests/unit/faucet/test_config.py
Fixes https://github.com/faucetsdn/faucet/issues/3294.
> Fix incorrect default for BGP connect mode.

- faucet/vlan.py
- tests/unit/faucet/test_config.py
Fixes https://github.com/faucetsdn/faucet/issues/3296.
> FAUCET vip cannot be a host address.

- faucet/dp.py
- tests/unit/faucet/test_config.py
Fixes https://github.com/faucetsdn/faucet/issues/3272
> Allow stack transit switches.

- faucet/acl.py
- faucet/conf.py
- faucet/dp.py
- tests/unit/faucet/test_config.py
Fixes https://github.com/faucetsdn/faucet/issues/3280
> Allow same tunnel ACL to be multiply applied

- faucet/valve.py
- faucet/valve_route.py
- tests/integration/mininet_tests.py
{"version": 1, "time": 1572388009.3293233, "dp_id": 453117464, "dp_name": "faucet-1", "event_id": 14, "L3_LEARN": {"eth_src": "e6:85:e0:fb:2f:26", "l3_src_ip": "10.0.0.1", "port_no": 8, "vid": 100}}
> Send events for L3 learns

- clib/mininet_test_base.py
- faucet/valve_of.py
- tests/integration/mininet_tests.py
Fixes https://github.com/faucetsdn/faucet/issues/3334
> flooded packets could be mirrored multiple times

- clib/mininet_test_topo.py
- docker/localtest.sh
- docs/conf.py
- docs/configuration.rst
- docs/tutorials/first_time.rst
- docs/vendors/hpe/README_Aruba.rst
- faucet/watcher_conf.py
- helper-funcs
- tests/codecheck/src_files.sh
- tests/fuzzer/display_packet_crash.py
- tests/fuzzer/fuzz_packet.py
- tests/unit/faucet/fakeoftable.py
I've dropped the problematic docker/runtests.sh changes from this pull request
> Cleanups and convenience updates

- Dockerfile.tests
- clib/clib_mininet_test_main.py
- docs/testing.rst
Implement a test debug mode for single test runner which drops into a pdb shell on assertion failure.
fixes #2894
> Implement test debug mode

- faucet/faucet.py
- faucet/port.py
- faucet/valve.py
- faucet/valve_flood.py
- faucet/valve_host.py
- faucet/valves_manager.py
- tests/integration/mininet_tests.py
- tests/unit/faucet/valve_test_lib.py
Fixes https://github.com/faucetsdn/faucet/issues/3400
> Keep cache on port down transition, to detect host moves easily.

- clib/mininet_test_base.py
- docs/configuration.rst
- tests/integration/mininet_tests.py
Locally ran test:
```
adding test FaucetDscpRewriteTest
----------------------------------------------------------------------
Ran 0 tests in 0.000s
OK
running 0 tests in parallel and 1 tests serial
test_untagged (mininet_tests.FaucetDscpRewriteTest) ... *** Error setting resource limits. Mininet's performance may be affected.
ok
----------------------------------------------------------------------
Ran 1 test in 29.534s
OK
test results
============
--- {}
...
```
> Need test to verify switches can match IP_DSCP field

- tests/unit/faucet/test_valve_stack.py
- tests/unit/faucet/valve_test_lib.py
Refactoring and adding some unit tests for edge port learning.
> Add edge_learn_port tests

- faucet/watcher.py
Actually increment inc so we don't get stuck in while loop.
> Avoid getting stuck in flowtable filename loop.

- clib/mininet_test_base.py
- faucet/faucet.py
- faucet/gauge.py
- faucet/prom_client.py
- faucet/valve_ryuapp.py
Verify Gauge has no exceptions also.
> Log version on startup.

- clib/mininet_test_base.py
- faucet/dp.py
- faucet/valve.py
- faucet/valve_of.py
- tests/integration/mininet_tests.py
> Warm Reload for Metering

- clib/clib_mininet_test_main.py
Fixes some test suite result printout problems (before it would run _mininet_tests.py_, print out results, then run _mininet_multidp_tests.py_ then print out both the results).
Fixes a problem where only tests from _mininet_tests.py_ would run when using the repeat option with tests selected in both _mininet_tests.py_ and _mininet_multidp_tests.py_.
> Iterate through modules when expanding tests

- faucet/valve.py
- faucet/valve_flood.py
- faucet/valve_route.py
- tests/unit/faucet/test_valve_stack.py
> Flood to stack ports for inter-VLAN routing

- faucet/valve.py
- tests/integration/mininet_multidp_tests.py
No state-change on cold-start prevented LACP flow-rules from being installed
Fixes #3460
> Install lacp flowrules on cold-start

- faucet/dp.py
- faucet/valve.py
- tests/unit/faucet/test_valve_config.py
Fixes https://github.com/faucetsdn/faucet/issues/3345
> Description only change is not an DP impactful change.

- clib/mininet_test_base.py
- faucet/conf.py
- faucet/dp.py
- faucet/port.py
- faucet/valve.py
- faucet/valve_host.py
- faucet/valves_manager.py
- tests/integration/mininet_tests.py
- tests/unit/faucet/test_config.py
- tests/unit/faucet/test_valve_config.py
- tests/unit/faucet/test_valve_stack.py
Fixes https://github.com/faucetsdn/faucet/issues/3420.
> Fix changes to DP level only config are not detected.

- tests/tolerance/mininet_tests.py
> Fix #3493 

- README.rst
This pull request just links directly to the line with supported hardware
to enable new users to find the list easier.
> Add direct link to supported hardware

- faucet/faucet_dot1x.py
- faucet/valve.py
- faucet/valve_coprocessor.py
- faucet/valve_lldp.py
- faucet/valve_outonly.py
- faucet/valve_switch.py
- faucet/valve_switch_stack.py
- faucet/valve_switch_standalone.py
- tests/codecheck/pytype.sh
- tests/integration/mininet_tests.py
- tests/run_unit_tests.sh
- tests/unit/faucet/test_valve_stack.py
Moving most VLAN flow creation out of valve.py.
Also fixes pytype problems.
> Migrate to valve manager pattern.

- faucet/vlan.py
- tests/unit/faucet/test_valve_stack.py
On consult from @gizmoguy, defaulting this True for inclusion in the next release.
> Default edge_learn stack_root to True

- faucet/dp.py
> Fix STATIC_TABLE_IDS feature.

- .travis.yml
> Upgrade docker on integration test jobs.

- .github/workflows/on-pr.yml
- .github/workflows/periodic.yml
- Dockerfile.fuzz-config
- Dockerfile.fuzz-packet
- Dockerfile.tests
* Upgrade to test-base:8.0.1.
* Fix fuzzer docker images.
* Tidy up our on PR github actions workflow.
Changes in test-base:8.0.1:
* Installs mininet python package in venv.
* Adds Open vSwitch v2.13.1.
* Smaller image size.
> Test base 8.0.1

- clib/fakeoftable.py
> Fix FakeOFTable reference for stack refactor

- faucet/valve.py
- tests/integration/mininet_tests.py
This allows the user to extend the LLDP emit interval using send_interval.
> Set LLDP interval to max of fast advertise interval and send interval

- faucet/acl.py
- faucet/dp.py
- faucet/valve_stack.py
- tests/unit/faucet/test_config.py
- tests/unit/faucet/test_valve_stack.py
Fixes https://github.com/faucetsdn/faucet/issues/3664
> Reference source of tunnel by stable ID to handle warm starts/new tunnel sources

- .github/workflows/tests-integration.yml
- Dockerfile.tests
- docker/runtests.sh
- docker/shard_tests.sh
Use github action runner to manage our faucet test docker in hopes this prevents the frequent stuck job problem we see.
> Use github action runner to manager docker.

- clib/clib_mininet_test_main.py
For example, the following will run tests with BGP in the name:
`FAUCET_TESTS="-i --regex .*BGP.*"`
> Integration test class name regex matching

- .github/workflows/tests-codecheck.yml
- .github/workflows/tests-integration.yml
- .github/workflows/tests-unit.yml
> Move to environment files instead of set-env.

- adapters/vendors/faucetagent/Dockerfile
> Enable go module mode.

- .github/workflows/release-docker.yml
> Migrate to supported docker/setup-buildx-action.

- .github/workflows/tests-codecheck.yml
- .github/workflows/tests-unit.yml
- codecheck-requirements.txt
- docker/pip_deps.sh
- docker/runtests.sh
- test-requirements.txt
* Update dependency pytype to v2020.11.3
* Disable running pytype on github actions with python3.5 as pytype no longer supports it
> Update dependency pytype to v2020.11.3

- adapters/vendors/rabbitmq/Dockerfile
* Switch to pyclean
* Make this a single layer docker image
> Fix rabbitmq adapter builds.

- faucet/port.py
- faucet/valve.py
- tests/unit/faucet/test_config.py
Add dot1x config test for invalid config.
> Remove explicit calls to dot1x manager.

- codecheck-requirements.txt
fixes this crash:
```
Traceback (most recent call last):
File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/venv/lib/python3.7/site-packages/pytype/single.py", line 97, in <module>
sys.exit(main() or 0)
File "/venv/lib/python3.7/site-packages/pytype/single.py", line 82, in main
return _run_pytype(options)
File "/venv/lib/python3.7/site-packages/pytype/single.py", line 93, in _run_pytype
return io.process_one_file(options)
File "/venv/lib/python3.7/site-packages/pytype/io.py", line 63, in wrapper
return f(*args, **kwargs)
File "/venv/lib/python3.7/site-packages/pytype/io.py", line 200, in process_one_file
loader = load_pytd.create_loader(options)
File …
```
> Update dependency pytype to v2021.5.6

- README.rst
- docs/intro.rst
* Advertise IRC channel on Libera instead of Freenode.
> Update getting help section in documentation.

- .github/workflows/release-python.yml
- .github/workflows/tests-codecheck.yml
- .github/workflows/tests-unit.yml
- faucet/valve_of.py
- setup.py
- tests/codecheck/min_pylint.sh
- tests/codecheck/pylint.sh
- tests/codecheck/src_files.sh
- tests/generative/integration/fault_tolerance_tests.py
- tests/integration/mininet_multidp_tests.py
- tests/unit/faucet/test_valve.py
- tests/unit/faucet/test_valve_config.py
- tests/unit/faucet/test_valve_dot1x.py
- tests/unit/faucet/test_valve_egress.py
- tests/unit/faucet/test_valve_stack.py
* Update test github action workflows.
* Improve pylint checking.
* Detect files with src_files.sh that were previously hidden.
fixes #3850
> CI improvements

- clib/valve_test_lib.py
- tests/unit/faucet/test_valve_config.py
This requires some re-factoring of parts of the unit-test framework
> Testing port additions and traffic across SIGHUP reloads

- faucet/vlan.py
- tests/unit/faucet/test_config.py
Fixes https://github.com/faucetsdn/faucet/issues/3858.
> Ensure VLAN MACs are always configured the same way, for comparison.

- docs/_static/tutorial/destroy_ns
- docs/external_resources.rst
- helper-funcs
New script files (mirroring existing instructions) and references to Faucet enabled projects
> Documentation updates

- .codecheck
- .pylintrc
- .stickler.yml
- codecheck-requirements.txt
- tests/codecheck/flake8.sh
- tests/codecheck/min_pylint.sh
- tests/unit/faucet/test_check_config.py
Introduce some tooling and cleanup that will be used if future PR's
> CodeCheck - part 1

- clib/valve_test_lib.py
- faucet/__main__.py
- faucet/check_faucet_config.py
- faucet/fctl.py
- tests/integration/mininet_tests.py
- tests/unit/faucet/test_check_config.py
- tests/unit/faucet/test_fctl.py
- tests/unit/faucet/test_main.py
- tests/unit/faucet/test_valve.py
- tests/unit/faucet/test_valve_config.py
- tests/unit/faucet/test_valve_dot1x.py
- tests/unit/faucet/test_valve_egress.py
- tests/unit/faucet/test_valve_of.py
- tests/unit/faucet/test_valve_stack.py
- tests/unit/faucet/test_valveapp_smoke.py
- tests/unit/gauge/test_main.py
- tests/unit/packaging/test_packaging.py
moving all of the remaining 'python' invocations to explicit 'python3' and small test case cleanup
> Simple cleanups

- clib/clib_mininet_test_main.py
- clib/fakeoftable.py
- clib/mininet_test_base.py
- clib/mininet_test_topo.py
- clib/valve_test_lib.py
- docs/conf.py
- faucet/acl.py
- faucet/dp.py
- faucet/faucet.py
- faucet/faucet_pipeline.py
- faucet/fctl.py
- faucet/gauge_pollers.py
- faucet/valve_acl.py
- faucet/valve_lldp.py
- faucet/valve_of.py
- faucet/valve_packet.py
- faucet/valve_pipeline.py
- faucet/valve_route.py
- faucet/vlan.py
- faucet/watcher.py
- tests/generative/integration/fault_tolerance_tests.py
- tests/integration/mininet_tests.py
- tests/unit/faucet/test_config.py
- tests/unit/faucet/test_fctl.py
- tests/unit/faucet/test_valve_egress.py
- tests/unit/gauge/test_gauge.py
3rd of 4 PRs : yet more vertical white space clean-ups
> CodeCheck - Part2c

- clib/docker_host.py
- clib/mininet_test_base.py
- faucet/faucet_bgp.py
- faucet/faucet_metrics.py
- faucet/gauge_influx.py
- faucet/valve_route.py
- faucet/valve_util.py
- tests/integration/mininet_tests.py
- tests/unit/faucet/test_check_config.py
The 1st of the manual flake8 cleanups
> CodeCheck - Part3a

- .codecheck
- .stickler.yml
- clib/clib_mininet_tests.py
- faucet/faucet_bgp.py
- faucet/faucet_dot1x.py
- faucet/faucet_event.py
- faucet/valve_of.py
- tests/generative/integration/fault_tolerance_tests.py
- tests/generative/unit/test_topology.py
The last of the manual flake8 changes, and improved enforcement for the future.
> CodeCheck - Part3b

- .codecheck
- .flake8
- .stickler.yml
- clib/clib_mininet_tests.py
- clib/mininet_test_base.py
- faucet/gauge_influx.py
- tests/codecheck/flake8.sh
- tests/generative/integration/fault_tolerance_tests.py
- tests/generative/unit/test_topology.py
Better fixes for some of the earlier fixes, and remove of 'noqa' overrides that are no longer needed
> CodeCheck - Part5

- .pylintrc
- .stickler.yml
- adapters/vendors/rabbitmq/rabbit.py
- adapters/vendors/rabbitmq/test_rabbit.py
- clib/clib_mininet_test_main.py
- clib/mininet_test_base.py
- faucet/valve_manager_base.py
- setup.py
- tests/codecheck/min_pylint.sh
- tests/codecheck/src_files.sh
- tests/integration/mininet_tests.py
The start of a tranche of pylint cleanups / corrections, etc
> pylint: part-1

- .github/workflows/tests-docs.yml
- codecheck-requirements.txt
- docker/runtests.sh
- docs/requirements.txt
> Separate codecheck test environment from doc build test environment 

- docker/install-faucet.sh
Shrinks docker image by about 10MB
> Remove git from final docker image.

- .github/workflows/tests-integration.yml
- Dockerfile.fuzz-config
- Dockerfile.fuzz-packet
* Upgrade to Open vSwitch 3.0.0
> Upgrade to test-base v11.0.0.

- setup.py
The Faucet python package fails to build wheel when installed via `pip --use-pep517  ...`. [pep517](https://peps.python.org/pep-0517/) builds packages with isolation and fails to copy the default faucet/ryu.conf files for migration within `install_configs()`. 
In my case, the Poetry package manager enforces this flag. There have been [similar issues](https://github.com/python-poetry/poetry/issues/6899) with other packages recently. Probably not a concern for most Faucet users, but the fix is simple.
The gist of the error is this:
```shell
File "/tmp/pip-build-env-q5mvrs66/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
exec(code, locals())
File "<string>", line 99, in <module>
File "<string>", line 79, in install_configs
File "<string>", line 54, in …
```
> Fix exception when pip install with --use-pep517 flag

- .github/workflows/tests-codecheck.yml
- .github/workflows/tests-docs.yml
- .github/workflows/tests-integration.yml
- .github/workflows/tests-unit.yml
The one we are currently using generates a number of deprecation notices.
> Change github action for detecting changed files.

- requirements.txt
- tests/unit/packaging/test_packaging.py
https://github.com/eventlet/eventlet/pull/817
> Install eventlet 0.34.3 for python 3.12 support.

- .github/workflows/release-python.yml
- .github/workflows/tests-codecheck.yml
- .github/workflows/tests-docs.yml
- .github/workflows/tests-unit.yml
> Standardise on python 3.12 for github action workflows
