src/ryu_faucet/org/onfsdn/faucet/gauge.py
Sometimes gauge stops working if a DP reconnects, because EventDPReconnected is not handled. In particular, despite the DP having reconnected, the polling threads continue timing out. Only if the the connection is closed (due to a TCP RST on the socket, for example) the gauge can recover by handling a disconnect followed by a connect. I have observed both cases while testing by rebooting my switch.
This code implements a reconnect handler that calls the same code as the connect handler, on reconnects. The reboot test shows logging and polling resume after a reconnect event.
Should the code should be stopping existing poller/logger threads before starting new ones?
=> Add DP reconnect handler for gauge

docker/Dockerfile.gauge
apt tries to start grafana during the gauge docker build and causes it to fail:
```
Failed to get D-Bus connection: Operation not permitted
dpkg: error processing package grafana (--configure):
subprocess installed post-installation script returned error exit status 1
```
This works around apt and allows the build to succeed.
=> Fix docker build for gauge

.gitignore, Makefile, docker/Dockerfile.dev, docker/Dockerfile.tests, docker/README.md, docker/runtests.sh, tests/faucet_mininet_test.py
This adds a new make target and some new docker containers:
- **Dockerfile.dev** uses the ryu-faucet package built by the new `make dockerdev` target instead of installing the current package with pip.
- **Dockerfile.tests** does the same thing as Dockerfile.dev, but runs the mininet tests as its entrypoint (it builds mininet and openvswitch, and other packages required for the unit tests).
This might not be the most elegant approach, and I'm unsure if it follows the intent of `docker/*`. Perhaps @gizmoguy and/or @rsanger could weigh in here? I'm happy to re-work this to make sense.
=> Add Dockerfiles for running locally-built faucet, and running mininet tests

src/ryu_faucet/org/onfsdn/faucet/valve.py
we are sending duplicate arp requests for routes that share the same gateway.
=> avoid sending duplicate arp

src/ryu_faucet/org/onfsdn/faucet/valve.py, tests/faucet_mininet_test.py
upon receiving arp reply, we only added the first route to forwarding table,
and ignore other routes that share the same gw.
=> fix the missing routes bug.

src/ryu_faucet/org/onfsdn/faucet/valve.py
If the flows added by learn_host_on_vlan_port() matching on eth_src have 
priority=self.db.highest_priority they can match packets destined to the controller,
which are supposed to match the flows added by learn_host_on_vlan_port().
I think that the former should have lower priority (self.db.high_priority maybe?
right now I just put a "-1").
=> Reduced priority of flows for learned hosts in 2:eth_src table

docker/Dockerfile, docker/Dockerfile.dev, docker/Dockerfile.gauge, docker/README.md
Main change is removing ENV statements and instead relying on the default
locations for relevant files. We have default values for the locations
of config and logging files, it makes sense for docker to use these also.
This also allows us to have the logging and config in separate directories
while using Docker.
Adds the -p argument to the docker README code sections as this is
almost certainly going to be needed by anyone deploying this.
Also makes the README fit 80 character terminals.
=> Tidy up the docker files and documentation slightly

tests/faucet_mininet_test.py
Not all HW switches can support ovs-ofctl to dump all the flows installed in its tables.
By using the already connected Ryu controller to fetch the flows (by starting it not only with the faucet app but also with the ofctl_rest app) we can be able to remove this contraint.
The format of the strings to search in the "dump-flows" output has been modified to correspond to the output provided by the Ryu ofctl_rest application.
All tests have been successfully run on Mininet with this change applied.
=> Use Ryu ofctl_rest API to dump flows instead of ovs-ofctl in unit tests

README.rst, src/ryu_faucet/org/onfsdn/faucet/dp.py
Partially addresses issue #112, by implementing the configuration file format changes needed to support multiple datapaths. Also adds some documentation on the changes made.
Everything should work fine but any additional testing and comments would be appreciated. I can add any additional features while I'm at it, if you like.
This change is backwards compatible with existing configuration files by adding a `version` field which defaults to `1` (the original format), so this should be safe to merge.
=> Add new configuration format with support for multiple datapaths

src/ryu_faucet/org/onfsdn/faucet/faucet.py, src/ryu_faucet/org/onfsdn/faucet/vlan.py, tests/faucet_mininet_test.py
IPv4 and IPv6 is implemented.
This is intended to serve as a "northbound" API for an external
system to import/export routes to/from FAUCET, since FAUCET
can do nexthop resolution for IPv4 and IPv6 itself - for example,
Quagga running on the host colocated with the controller. The
external system should do all necessary route filtering.
BGP is implemented per VLAN (bgp_port is what TCP port FAUCET
will listen on - must be different per VLAN).
vlans:
100:
bgp_port: 9179
bgp_as: 1
bgp_routerid: '1.1.1.1'
bgp_neighbor_address: '127.0.0.1'
bgp_neighbor_as: 2
Restrictions:
* bgp_routerid must be an IPv4 address, even when peering over IPv6.
* Only one neighbor is supported (since intended use is an API).
* Receiving routes is not yet implemented.
* Port status updating advertisements is not …
=> Implement BGP advertisement of controller IPs and static routes.

Dockerfile.gauge
Install 'wheel' pip package manually to supress errors.
Install wget apt package so that Docker can be built.
=> Fix building of gauge Dockerfile.

src/ryu_faucet/org/onfsdn/faucet/valve.py, tests/faucet_mininet_test.py
ACLs now have a new action - output:
acls:
1:
- rule:
dl_dst: "01:02:03:04:05:06"
actions:
output:
dl_dst: "06:06:06:06:06:06"
port: 2
Output takes an argument, port (the pipeline outputs to a given
port, then stops processing).
Output can take another argument, dl_dst. If set, the
packet's Ethernet destination is rewritten to this value
before output.
=> Implement policy based forwarding.

src/ryu_faucet/org/onfsdn/faucet/faucet.py, src/ryu_faucet/org/onfsdn/faucet/valve.py, tests/faucet_mininet_test.py
FAUCET can now can receive and announce routes over BGP, both IPv4 and IPv6.
FAUCET will install routes its in FIB from the external peer, provided that the nexthop is in the same subnet as one of the VLANs' IP addresses. FAUCET will do the nexthop resolution itself.
See FaucetUntaggedBGPIPv4RouteTest and FaucetUntaggedBGPIPv6RouteTests for examples of how to send routes to FAUCET (using exabgp in this instance).
=> Complete BGP support.

src/ryu_faucet/org/onfsdn/faucet/valve.py
This shouldn't have passed the test :)
I'm trying to figure out how to write a unitest for add_route (when next-hop is resolved) and del_route
I added "process" to exabgp to program the bgp updates, but it does not work. Somehow, exabgp says "permission denied" when the control script is placed inside a temp dir.
=> Fix a (serious) mistake: missing fib_table argument in add_route

src/ryu_faucet/org/onfsdn/faucet/faucet.py, src/ryu_faucet/org/onfsdn/faucet/valve.py, tests/faucet_mininet_test.py
Some tests can be run in parallel by dynamically allocating ports for for OpenFlow/control.
Some tests are still serial (they use hardcoded ports). FaucetSingle tests should be refactored to also dynamically allocate ports which will also speed the tests up.
=> Make tests run in parallel by dynamically allocating ports as needed.

src/ryu_faucet/org/onfsdn/faucet/valve.py, tests/faucet_mininet_test.py
Pipeline matches are now documented, and enforced by tests.
Add IPv4 route test helpers.
Use "ofmsgs" instead of "flowmods" consistently in valve.py.
=> Add test-enforced pipeline match documentation, and other incremental cleanup.

README.docker.md
Add extra command to help file that tells you how to run the Docker tests to make it clear that openvswitch module must be loaded prior to the Docker being started.
=> Openvswitch module must be loaded on the docker host for tests to run.

README.docker.md
We no longer maintain the faucet-gauge docker.
=> Update docker documentation.

tests/faucet_mininet_test.py
I was looking through this, and noticed that multiple `vlans` sections would get added to the test Faucet config. I fixed that, and tidied up some of the nastier parts of the string concatenation while I was at it.
=> FaucetMultipleDPTest: Tidy up and fix mixing tagged/untagged hosts

src/ryu_faucet/org/onfsdn/faucet/valve.py
At the moment we silently crash if someone plugs a cable into a faucet
controlled switch that isn't listed in the config file.
This bug is caused by old code leftover from Valve. I think this is bad
default behaviour so have removed the old code.
=> Don't crash faucet if someone plugs a cable into an unconfigured port.

README.rst
Adds syntax highlighting for configuration snippets, fixes mistakes and outdated configuration syntax, and adds a deprecation notice for the version 1 configuration file format.
=> Update README.rst on config file format

docker-compose.yaml
I noticed the following when trying to use the existing docker-compose.yaml:
The config file for gauge wasn't pointing at the new yaml one.  Fixed with an env var
The grafana data wasn't persistant.  Fixed with a bind mount to the file system (yes there are other ways to do this but there you go)
The containers didn't restart if they failed.  They do now with restart: always
Faucet wasn't being started (as gauge and faucet have been split now).  If people don't want it started then it's easier for them to remove it from the example than it is for other people to work out how to add it.
=> changes to docker-compose.yaml

all-ports-dashboard.json
The following dashboard should slot straight into the grafana install.
You do need to configure the datasource and make it 'default' first thought.
There are three sections.  One is a template dropdown with all your ports in it.  You can select them all, one, or multiple
The top graph shows bps.  
The bottom graph shows in vs out percentage for all selected ports.  
It's a good example for people to build from.
I have not extended this to support multiple dps, but that should be as simple as extending the queries and adding another template variable.
=> adding an example grafana dashboard

tests/faucet_mininet_test.py
At the moment a single bad response from the ofctl REST API will cause us to fail a test.
Make this more robust by catching ValueError (parsing) exceptions and doing our normal timeout business.
This should make tests slightly more reliable on non-docker systems. I'm still tracking down a few other issues to make this fully reliable.
=> Make tests more robust when we get a bad JSON reply.

tests/faucet_mininet_test.py
On slower systems the 1 second sleep might not be long enough to start tcpdump and have it capturing packets before we inject the test packets.
Move the packet creation into the output check loop so that we retry sending test packets if tcpdump doesn't get them the first time.
This approach still isn't 100% perfect, ideally we would be able to poll tcpdump to work out when it's ready and capturing packets, but I couldn't find a reliable way of doing this.
=> Rework ordering of tcpdump tests.

tests/README.md, tests/faucet_mininet_test.py
Mininet likes to leave lots of temporary system configuration lying around if we don't cleanly exit a test run. Add a mode for cleaning this configuration up.
=> Add cleanup mode for unit tests to cleanup after failed runs.

README.rst, src/ryu_faucet/org/onfsdn/faucet/config_parser.py, tests/config/testconfigv2-acls.yaml, tests/config/testconfigv2-dps.yaml, tests/config/testconfigv2-vlans.yaml, tests/config/testconfigv2.yaml, tests/faucet_mininet_test.py, tests/test_config.py
Adds functionality, documentation and tests for allowing DPs, VLANs and ACLs to be defined in separate/additional configuration files.
Basically, an `include` and `include-optional` section were both added, which both are lists of either absolute or relative (to the config file) paths, and the configuration dictionary from the main configuration is updated with that of the included files. Files are parsed in this order: main configuration file, required include files, optional include files (both in the list order they are defined in). Duplicate DPs/VLANs/ACLs get replaced with the last one read.
See the commits for more details.
=> Add support for required and optional include files

src/ryu_faucet/org/onfsdn/faucet/valve_flood.py
Extend the mask to cover exactly the IEEE 802 OUI space so that it
properly excludes other issued vendor OUIs.
The previous mask would have matched (and flooded) multicast MAC addresses in
unrelated OUIs outside of the IEEE 802 OUI.  For example, multicast addresses within
the (issued) OUI 00:80:C3 would have also matched and flooded.
Not seen in the wild.  Spotted during code inspection.  This code change has not
been tested.
=> valve_flood: correct mask on IEEE 802.x multicast MAC OUI

src/ryu_faucet/org/onfsdn/faucet/config_parser.py, src/ryu_faucet/org/onfsdn/faucet/faucet.py, tests/config/testconfigv2-acls.yaml, tests/config/testconfigv2-includeloop.yaml, tests/test_config.py
Some improvements to configuration file handling.
* Fixes an infinite loop situation where include files could be recursively loaded, by keeping track of open files and logging an error (`include`) or skipping the file (`include-optional`) if an include file loop is found.
* Only commits changes an include file makes to the configuration if it was successfully loaded, by storing changes in a data structure until the end of `_dp_include()`, after all checks are done.
* Only reloads the Faucet configuration upon `SIGHUP` if changes to the configuration were found in some way. It does this when one of the following conditions are met:
* The `FAUCET_CONFIG` environment variable has changed
* An include file that was not loaded now exists
* A file that has been loaded no longer exists
* Loaded …
=> Configuration fixes and additions

src/ryu_faucet/org/onfsdn/faucet/dp.py, src/ryu_faucet/org/onfsdn/faucet/port.py, src/ryu_faucet/org/onfsdn/faucet/valve.py, src/ryu_faucet/org/onfsdn/faucet/valve_acl.py, src/ryu_faucet/org/onfsdn/faucet/vlan.py, tests/faucet_mininet_test.py
incrementally reloading Faucet configs
Detects what changes have been made and reload only what affected by the changes.
Following changes are detectable: 
- port configs change such as native_vlan, unicast_flood, acl_in....
- ACL changes
- VLAN changes: controller_ips....
=> Incrementally reload faucet config

tests/fakeoftable.py, tests/test_valve.py
I have rebuilt the original valve unit tests.
This involves using a custom made simulation of a flow table, modelled on OVS's ofproto/trace command. The goal here is to have a system that does not require root to be run.
If there is another openflow 1.3 dp implementation that supports an ofproto/trace like function and can be run entirely in user space we should probably use that instead.
However I dont think supporting this will be too onerous. I have tried to make everything as explicit and as easy to understand as possible.
The unit tests currently only cover basic switching/vlan functions.
=> Valve Unittests

src/ryu_faucet/org/onfsdn/faucet/watcher.py
OpenvSwitch indicates unsupported statistics by returning UINT64_MAX which currently crashes Gauge due to #355 and #353.
This PR fixes one part of the equation.
=> Throw away unsupported statistics returned by OpenvSwitch.

src/ryu_faucet/org/onfsdn/faucet/aruba/README.md
I have written a small readme on how to go about using Faucet with Aruba switches. It talks about how to configure both the Aruba switch and faucet to make it work.
=> Add a README for using Faucet on Aruba switches

.travis.yml, setup.py, tests/faucet_mininet_test.py
Allows us to correctly parse ryu 4.10 as newer than 4.9.
Fixes #369.
=> Use packaging library for parsing test dependency versions.

src/ryu_faucet/org/onfsdn/faucet/faucet.py
The exception log was only logging CRITICAL messages, but was logging exceptions at ERROR.
=> Don't filter exceptions from the exception log

src/ryu_faucet/org/onfsdn/faucet/dp.py, src/ryu_faucet/org/onfsdn/faucet/valve.py, src/ryu_faucet/org/onfsdn/faucet/valve_flood.py, src/ryu_faucet/org/onfsdn/faucet/valve_of.py, src/ryu_faucet/org/onfsdn/faucet/valve_route.py, tests/faucet_mininet_test.py, tests/faucet_mininet_test_base.py
To enable, add "group_table: True" to each dp's config.
group table is automatically disabled if stacking is used.
=> use GROUP tables for FIB and VLAN flooding

src/ryu_faucet/org/onfsdn/faucet/gauge.py
This means that the exception log doesn't filter out exceptions.
=> Change logging priority for exceptions in gauge.

src/ryu_faucet/org/onfsdn/faucet/check_faucet_config.py
and exits with 0 if all configs can be parsed, or non-0 if not.
faucet@faucet:~/faucet/src/ryu_faucet/org/onfsdn/faucet$ ./check_faucet_config.py /etc/ryu/faucet/faucet.yaml
Error in file /etc/ryu/faucet/faucet.yaml (while scanning for the next token
found character '\t' that cannot start any token
in "/etc/ryu/faucet/faucet.yaml", line 9, column 1)
faucet@faucet:~/faucet/src/ryu_faucet/org/onfsdn/faucet$ echo $?
255
=> Add check_faucet_config.py, which parses a list of FAUCET configs,

Dockerfile, Dockerfile.tests, requirements.txt, src/ryu_faucet/org/onfsdn/faucet/faucet.py, src/ryu_faucet/org/onfsdn/faucet/gauge.py, src/ryu_faucet/org/onfsdn/faucet/valve_of.py, src/ryu_faucet/org/onfsdn/faucet/watcher.py
InfluxDB automatically derives type from the first value inserted, so unfortunately this means timeseries will have to be manually converted.
=> InfluxDB: handle connection errors, and switch from uint64 to float64 to avoid InfluxDB int64 limits.

src/cfg/etc/ryu/faucet/gauge.yaml-dist
This is necessary so that developers don’t have to worry about setting
up CouchDB, but have access to flow tables in text format that they can
look at.
=> Added file based storing option for flow tables

src/ryu_faucet/org/onfsdn/faucet/config_parser.py, src/ryu_faucet/org/onfsdn/faucet/dp.py, src/ryu_faucet/org/onfsdn/faucet/router.py, src/ryu_faucet/org/onfsdn/faucet/valve.py, src/ryu_faucet/org/onfsdn/faucet/valve_route.py, tests/config/testconfigv2-dps.yaml, tests/faucet_mininet_test.py
vlans:
100:
description: "100"
faucet_vips: ["10.100.0.254/24"]
200:
description: "200"
faucet_vips: ["10.200.0.254/24"]
routers:
router-1:
vlans: [100, 200]
Hosts in VLAN 100 (using a gateway of 10.100.0.254) will be able to reach hosts in VLAN 200 (hosts there using a gateway of 10.200.0.254).
Only one router, routing between all VLANs is currently supported.
=> Implement inter-VLAN routing

tests/faucet_mininet_test.py
While running the test cases with an hardware switch and using ports different from 1, 2, 3, and 4 I noticed that some test were failing because they were looking for strings like "in_port: 1" or "OUTPUT:1". I replaced all occurrences of these strings using the values in self.port_map instead.
Also, in test FaucetGroupTableTest.test_group_exist the regex string was trying to match the string `'"table_id": 7,.+"dl_vlan": "100"'` but this string may match the wrong flow entry (using group 4196 instead of group 100) depending on the order of the flows in the multipart reply. 
These are the existing flows:
```
{"priority": 9001, "hard_timeout": 0, "byte_count": 0, "duration_sec": 13, "actions": ["GROUP:100"], "duration_nsec": 2000000, "packet_count": 0, "idle_timeout": 0, "cookie": …
```
=> Remove hardcoded port_no from faucet_mininet_test.py

faucet/valve_host.py
To enable hard_timeout, add 'hard_timeout_enabled: True' to dp config.
This PR is to replace PR #485
=> add jitter to rule timeout to avoid re-learning a bunch of host simultaneously.

Dockerfile, Dockerfile.gauge, Dockerfile.tests
Fixes our Docker builds which are currently failing.
=> Python dependency netifaces requires GCC to be installed.

faucet/valve_acl.py, faucet/valve_of.py, tests/faucet_mininet_test.py
- rule:
dl_dst: "01:02:03:04:05:06"
actions:
output:
dl_dst: "06:06:06:06:06:06"
vlan_vids: [123, 456]
port: acloutport
You can specify multiple VIDs, and they are pushed left to right.
Each header will have ether type 0x8100.
Requires OVS dev + https://github.com/openvswitch/ovs/commit/f0fb825a3785320430686834741c718ff4f8ebf4.
=> Implement multiple VLAN header push support in ACLs.

faucet/valve.py, tests/faucet_mininet_test.py
======================================================================
FAIL: __main__.FaucetConfigReloadTest.test_port_change_permanent_learn (subunit.RemotedTestCase)
__main__.FaucetConfigReloadTest.test_port_change_permanent_learn
----------------------------------------------------------------------
_StringException: Traceback (most recent call last):
File "./faucet_mininet_test.py", line 895, in test_port_change_permanent_learn
self.verify_tp_dst_blocked(5001, first_host, second_host)
File "/home/faucet/faucet/tests/faucet_mininet_test_base.py", line 618, in verify_tp_dst_blocked
'', first_host.cmd('timeout 10s nc %s %u' % (second_host.IP(), port)))
File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual
assertion_func(first, second, msg=msg)
File …
=> Rollback due to FaucetConfigReloadTest.test_port_change_permanent_learn flakeyness.

faucet/valve.py, tests/faucet_mininet_test.py
Reopen for #527. 
I could not replicate the error appeared on #531. But the reason could be the lack of delay for Faucet to finish the flow installation. I added time.sleep after the hup_faucet, hope this will fix it.
=> a fix for permanent learning port fails to learn when reloading config

setup.py
Fix faucet setup.py for issue #497
=> Use py2 and py3 compatible io.read() instead of read().

faucet/valve_acl.py, tests/faucet_mininet_test.py
Rewrites the destination MAC address, while still allowing the packet through the Faucet pipeline (to be switched based on the new MAC dest).
So an ACL can now look like:
```        
- rule:
dl_dst: "00:00:00:00:00:02"
actions:
allow: 1
dl_dst: "00:00:00:00:00:03
```
=> Destination MAC rewrite

setup.cfg
Having a installable faucet under pip3 is nicer than having a description-file.
Closes #497
=> Work-around a PBR python3 bug.

faucet/config_parser_util.py
With resource warnings turned on in python3, I see the following warning:
[WARNING] py.warnings: /code/faucet/faucet/config_parser_util.py:64: ResourceWarning: unclosed file <_io.TextIOWrapper name='/code/faucet/faucet.yml' mode='r' encoding='UTF-8'>
=> Fix python3 resource warning in config_parser.py.

faucet/port.py, faucet/valve.py, faucet/valve_host.py, tests/faucet_mininet_test.py, tests/faucet_mininet_test_base.py
Limits the number of hosts that can be learnt on a port at one time. Should behave in a similar way to VLAN max_hosts.
new config option
```yaml
interfaces:
4:
native_vlan: 100
description: "b4"
max_hosts: 3
```
=> max_hosts for port

docs/vendors/ovs/README_OVS-DPDK.rst
Also showing that with OVS 2.7 you can use interface name as compared to dpdk<n> for port numbering
=> Fixed typos

faucet/check_faucet_config.py, setup.cfg
Makes it easier to run check_faucet_config from ansible if it is installed as a script.
Tests are passing : https://travis-ci.org/gizmoguy/faucet/builds/233877932
=> Install a console script for check_faucet_config.

requirements.txt
We require a couple commits that aren't in a released version of ryu:
osrg/ryu@6d35bb8
osrg/ryu@a197d87
=> We need to install ryu from git for now.

setup.cfg
We no longer support python2. We are fully tested against python3.5 (and likely other versions of python3)
=> We no longer support python2. We are fully tested against python3.5

docs/self_signed_certs.md
Self-signed certificates have the benefit of not relying on a CA but can still provide certain security of the control plane network. This document describes the steps needed to test if a switch supports self-signed certificates.
=> Add directions for testing self-signed certificates

faucet/valve_flood.py
Broadcast packets are dropped at stack ports because they have vlan-tag stripped off. Output stack port actions should be placed before local port actions.
=> stack ports should not have vlan-tag stripped

faucet/valve.py, faucet/valve_packet.py, faucet/valve_route.py, faucet/vlan.py, tests/faucet_mininet_test_base.py, tests/faucet_mininet_test_unit.py
FAUCET's MAC address used to be globally hard coded. You can now configure it on a per VLAN basis.
vlans:
100:
faucet_vips: ["fc00::1:254/112"]
faucet_mac: "0e:00:00:00:00:99"
=> FAUCET MAC address now configurable per VLAN

docs/README_install.rst, setup.py
If pbr is not installed, easy_install is required to get latest
version. Setting the PBR_VERSION env variable is breaking the
process. See: https://bugs.launchpad.net/pbr/+bug/1256138
This is a workaround by using a temp METADATA file to force
force faucet's version.
Also the package in pypi is called 'faucet' and not 'ryu-faucet'
Fixes #724
=> Fix pip install

etc/ryu/faucet/aruba_pipeline.json
Now that FAUCET supports meter instruction in user defined ACLs,
adding meter instruction in the pipeline definition for Aruba devices in tables 'Port ACL' and 'VLAN ACL'.
=> Add meter instruction in aruba_pipeline.json

faucet/valve_of.py, faucet/valve_route.py, tests/faucet_mininet_test_base.py, tests/faucet_mininet_test_unit.py
We now allow setting a mask on transport ports, which is key to ACL rule scaling.
Eg:
- rule:
dl_type: 0x800
nw_proto: 6
tp_dst: 1024/1024
actions:
allow: 0
TCP_DST et al are marked "not maskable" in the OF1.3.5 spec (p.127, https://www.opennetworking.org/images/stories/downloads/sdn-resources/onf-specifications/openflow/openflow-switch-v1.3.5.pdf). However, OVS has set a precedent since version 1.6/2012 of supporting masking (http://openvswitch.org/support/dist-docs/ovs-fields.7.pdf, https://mailman.stanford.edu/pipermail/openflow-discuss/2012-April/003139.html).
Multiple hardware has also been tested with mask support.
=> Allow masks to be set on UDP/TCP/SCTP ports

Dockerfile.gnmi, gnmi/README.md, gnmi/certs/generate.sh, gnmi/get.sh, gnmi/run_target.sh
This docker contains a simple environment to test gNMI. It generates certificates for use with the provided gNMI tools. These are a gNMI Target binary and a gNMI Get binary. The gNMI Get can be used against other implementations or the existing mock gNMI Target, which for now simply returns the executed Request.
=> Add a docker image to facilitate gNMI testing.

faucet/dp.py, faucet/faucet.py, faucet/valve.py, faucet/valve_host.py, faucet/valve_of.py, tests/faucet_mininet_test_unit.py
This is to replace #485.
By replacing hard-timeout with idle-timeout, we can miminize packet-ins to zero and keep the network working for all active hosts without Faucet running.
It is configurable.
=> Eliminate hard-timeout, zero packet-ins

faucet/valve_host.py, tests/faucet_mininet_test_unit.py
I found out the cause for the occasion of test failure. Renew cache_time during the host_expire interval causes confused that host is recently learned so the learn_host_on_vlan return empty flowmod.
Also, because dst flows stay longer than src flows, we should wait for few seconds until they are removed from tables.
I run the tests multiple times on my PC and see a consistent result.
=> a fix for idle-timeout host refreshing

tests/faucet_mininet_test_unit.py
I figured out the cause for unreliable tests. The test uses timeout 8secs; this plus with a jitter, sometimes making it to 13. The idle-timeout plus 2 for dst flow, hence the dst flows timeouts at 15 sec. The test waits for flowremoved at max 15 sec making the tests fails.
I reduced the learn timeout to 1sec in tests. that solved the problem.
=> reduce learn timeout setting in Idle-timeout test to make it reliable.

faucet/faucet.py, faucet/faucet_bgp.py, faucet/faucet_metrics.py, faucet/gauge.py, faucet/gauge_prom.py, faucet/valve.py, tests/faucet_mininet_test_base.py
Gauge uses dp_id rather than dpid for prometheus labels.
Tests passing - https://travis-ci.org/gizmoguy/faucet/builds/269856691
=> Make prometheus dp_id label consistent.

faucet/__init__.py, requirements.txt
This PR will provide the running version of faucet (in faucet.__version__) by using PBR to parse the version info.
Tests passing - https://travis-ci.org/gizmoguy/faucet/builds/271654005
=> Add version info to faucet.__all__.

docs/vendors/noviflow/README_noviflow.rst
Compared to FAUCET v1.5.7, the latest version v1.6.4 requires a couple of additional match fields in table 2 in order to run the entire regression test suite. I included them in the NoviFlow docs.
=> Add matchfields required for regression tests in noviflow docs

Dockerfile.tests, faucet/valve_acl.py, tests/faucet_mininet_test_base.py, tests/faucet_mininet_test_unit.py
actions:
output:
vlan_vids: [{vid: 123, eth_type: 0x88a8}, 456]
If eth_type is present, it is used instead of default (0x8100).
=> Allow configuration of VLAN tag type in ACL rule

etc/ryu/faucet/faucet.yaml, etc/ryu/faucet/gauge.yaml
This PR fixes two issues:
Our example faucet.yaml config refers to a non-existent ACL rule which causes faucet to have an exception on startup.
Our example gauge configuration doesn't turn on prometheus support by default.
=> Example config fixes

tests/faucet_mininet_test_unit.py
The `faucet_mininet_test_unit.FaucetUntaggedPrometheusGaugeTest.test_untagged` test case was checking always the statistics related to port `1` instead of using the dynamic value specified in `hw_switch_config.yaml`. Now it uses `self.port_map["port_1"]` instead
=> remove hardcoded port 1 from faucet_mininet_test_unit.py

faucet/dp.py, faucet/faucet.py, faucet/gauge.py, faucet/valve_util.py
This pull request introduces a `get_setting` accessor to replace os.getenv() in obtaining the setting environment variables. The defaults for all the environment variables are now centralized in valve_util. In addition, there is a new FAUCET_PIPELINE_DIR setting for the `pipeline_dir` default used in dp.py.
It was possible for a local environment change to FAUCET_CONFIG/GAUGE_CONFIG to change the config file path when it was reloaded -- I removed this. I'm not sure if this was used. (see reload_config in faucet.py/_load_config in gauge.py).
I'm not sure why there is a per-datapath pipeline_dir setting; I can understand why a "pipeline_file" setting might be useful for specific datapaths.
=> Add valve_util.get_setting() and use it instead of os.getenv().

etc/ryu/faucet/faucet.yaml
Removed content under sw2 in the faucet.yaml config file, which was causing a crash when starting the docker.
=> Remove sw2 from config; fixing unhandled exception on startup

tests/test_check_config.py
realized after Travis ran on #1205 that `test_check_config.py` is actually being tested 😃 , so adding a specific test to run there as well.
=> add test for checking VLANs resolve on routers

faucet/dp.py, faucet/faucet.py, faucet/valve_util.py, requirements.txt, tests/faucet_mininet_test_unit.py
Environment variable FAUCET_CONFIG_STAT_RELOAD must be set to not-empty.
E.g.
docker run -e FAUCET_CONFIG_STAT_RELOAD=1 -t faucet/faucet
=> Optionally detect config file changes on disk and apply new config without needing HUP.

faucet/valve_util.py
faucet@faucet:~/faucet$ PYTHONPATH=. FAUCET_LOG=STDOUT FAUCET_EXCEPTION_LOG=STDERR ryu-manager faucet.faucet
loading app faucet.faucet
loading app ryu.controller.ofp_handler
creating context faucet_experimental_api
instantiating app None of DPSet
creating context dpset
instantiating app faucet.faucet of Faucet
instantiating app ryu.controller.ofp_handler of OFPHandler
Nov 27 23:55:09 faucet INFO     Add new datapath DPID 260367051208429 (0xeccd6d9936ed)
Nov 27 23:55:09 faucet ERROR    features_handler: unknown datapath DPID 123917682135232 (0x70b3d56cd0c0)
=> Allow logging to stdout/err:

faucet/faucet.py, faucet/valve.py
Dec 03 17:03:32 faucet ERROR    DPID 1004415909 (0x3bde2ba5) OFError version=0x4,msg_type=0x1,msg_len=0x4c,xid=0xf167218c,OFPErrorMsg(code=9,data=byt
earray(b'\x04\x0e\x00H\xf1g!\x8c\x00\x00\x00\x00Z\xdc\x15\xc0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00#\x8b\xff\xff\xff\xff\x00\x00\x0
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x17\x80\x00\x00\x04\x00\x00\x00\x01\x80\x00\x14\x01'),type=4) caused by version=0x4,msg_type=0xe,ms
g_len=0x48,xid=0xf167218c,OFPFlowMod(buffer_id=4294967295,command=0,cookie=1524372928,cookie_mask=0,flags=0,hard_timeout=0,idle_timeout=0,instruction
s=[],match=OFPMatch(oxm_fields={'in_port': 1, 'tcp_dst': 5001, 'ip_proto': 6}),out_group=0,out_port=0,priority=9099,table_id=0)
=> When an OFError occurs, correlate with the offending XID.

faucet/acl.py, faucet/dp.py, faucet/port.py, faucet/vlan.py, faucet/watcher_conf.py
It would be good for someone to do a basic editing check of this. Not sure how this will render with the readthedocs stuff but I figured it would be best to get it up and on git earlier rather than later.
=> Add documentation of config to Conf object source files

docs/testing.rst
Newer versions of Dockerd explicitly disable ipv6 on loopback, this is a work-around to bring it back.
=> Add docker flag for starting with ipv6 enabled.

faucet/faucet_experimental_event.py
Fixes #1388, we now gracefully handle the case that we don't have permissions to access to the socket directory.
=> Event socket permissions checks

faucet/valve_route.py, faucet/vlan.py, tests/faucet_mininet_test_unit.py
vlans:
100:
faucet_vips: ["10.0.0.254/24"]
targeted_gw_resolution: True
If a host has been resolved as a gateway successfully, on the first retry only, target the re-resolution attempt (ARP or NS) directly to the last known port. If not successful, subsequent retries will be flooded as normal.
This reduces gateway resolution workload and gateway resolution noise generally.
=> Implement targeted_gw_resolution

etc/ryu/faucet/tfm_pipeline.json
Update the generic pipeline so that the faucet test suite will pass if 'GenericTFM' is used as hardware type
- Add missing match capabilities in table 0 (Port ACL)
- Add missing action capabilities in table 4 and 5 (IPv4/IPv6 FIB)
=> Update the generic TFM pipeline

docker/build-faucet-pi-on-pi.sh
latest will now point to latest released version of faucet rather than faucet@master on git.
=> Update rasp pi build script to use our new docker tag system.

docs/configuration.rst, faucet/dp.py, faucet/port.py, faucet/valve.py, faucet/vlan.py, tests/faucet_mininet_test_base.py, tests/faucet_mininet_test_unit.py
Configuring output_only: True on an interface, adds an explicit drop rule for all packets from that interface (for accounting).
ACLs/mirror to a port,  implicitly enable output_only: True on that port.
=> Add output_only option to interface.

faucet/__main__.py
Here is a start on a Faucet launcher script. The goal is to make Faucet slightly easier to use from the command line. Under the covers, it just runs ryu-manager.
To run faucet:  `python -m faucet`
To run gauge:  `python -m faucet --gauge`
Faucet and Gauge continue to use environment variables for configuration. Future changes could translate arguments to environment variables as needed.
```console
$ python -m faucet --help
usage: faucet [-h] [-v] [--gauge] [--ryu-app APP]
Faucet SDN Controller
optional arguments:
-h, --help     show this help message and exit
-v, --version  print version and exit
--gauge        run Gauge instead
--ryu-app APP  add Ryu app (can be specified multiple times)
```
There are several Ryu arguments that still need to be handled before this could replace …
=> Proof of concept for Faucet launcher script

faucet/valve_of.py
`valve_flowreorder()` already reorganises the list of messages that must be sent to the switch to send them in the following order:
1. flow_mod delete, group_mod delete
2. barrier
3. group_mod add
4. barrier
5. everything else
This doesn't take into consideration meters, which should be treated similarly to groups:
1. flow_mod delete, group_mod delete, meter_mod delete
2. barrier
3. group_mod add, meter_mod add
4. barrier
5. everything else
=> valve_flowreorder should take meter_mod messages into consideration

faucet/dp.py, faucet/faucet.py, faucet/port.py, faucet/valve.py, faucet/valve_acl.py, faucet/valve_packet.py, tests/faucet_mininet_test_unit.py
Send basic LLDP beacon on configured ports. Intended to send custom TLVs (such as voice VLANs). 
Not a topology discovery or verification service.
dp:
lldp_beacon:
send_interval: 5
max_per_interval: 5
interfaces:
1:
native_vlan: 100
lldp_beacon:
enable: True
=> Implement trivial LLDP beacon service (and fix for ACL description in rules).

faucet/dp.py, faucet/port.py, faucet/valve.py, faucet/valve_packet.py, tests/faucet_mininet_test_unit.py
interfaces:
1:
native_vlan: 100
lldp_beacon:
enable: True
org_tlvs:
- {oui: 0x12bb, subtype: 2, info: "01406500"}
for example, encodes voice tagged VLAN 50.
=> LLDP beacon service can configure arbitrary org-specific TLVs

docs/configuration.rst, faucet/port.py, faucet/valve.py, tests/faucet_mininet_test_base.py, tests/faucet_mininet_test_unit.py
At a port level, you can now say:
interfaces:
1:
description: "static port"
opstatus_reconf: False
This causes FAUCET to ignore the operational status of a port (meaning all flows relevant to this port will be left in place, even if the switch notifies that the port is down).
This is useful, for example to minimize flow changes for low performance OFAs, or to maintain ACL counters.
=> Implement port level opstatus_reconf option.

docs/vendors/noviflow/README_noviflow.rst
A couple of minor changes to configure the table match fields in NoviFlow switches for the automated test cases:
- icmpv6 match moved to table 6 instead of 3
- add match fields for FaucetIPv6TupleTest
=> Noviflow docs update for faucet v1.6.18

tests/faucet_mininet_test_unit.py
`FaucetDeleteConfigReloadTest` uses port 99 in the configuration file, which causes NoviFlow switches to complain about a BAD_MATCH / BAD_VALUE since this port doesn't exist.     
Would the test achieve its goal if one of the ports of `hw_switch_config.yaml` is used instead?   
I tried running it on OVS and it passes with this change, but I don't know if we actually need to use a different port.
=> avoid hardcoded port in FaucetDeleteConfigReloadTest

faucet/conf.py, faucet/dp.py, faucet/port.py, faucet/valve.py, tests/faucet_mininet_test_unit.py, tests/test_config.py
Provide sensible defaults for system_name and port_descr as described in #1539. Includes some basic tests for the new behaviour and configuration.
=> Provide sensible defaults for system_name and port_descr LLDP TLVs

docker/supervisord.gauge.conf, docs/installation.rst, docs/vendors/lagopus/README_Lagopus.rst, docs/vendors/noviflow/README_noviflow.rst, docs/vendors/ovs/README_OVS-DPDK.rst, etc/systemd/system/faucet.service, etc/systemd/system/gauge.service, tests/faucet_mininet_test_topo.py
This deprecates starting faucet with "ryu-manager" the faucet start script should now be used instead.
=> Switch to using faucet startup script by default

docs/configuration.rst, etc/ryu/faucet/faucet.yaml, faucet/dp.py, faucet/port.py, faucet/valve.py, faucet/vlan.py, tests/faucet_mininet_test_unit.py, tests/test_check_config.py, tests/test_config.py
Fix for issue #972
* Adds acls_in option to vlans and ports which take a list of acls.
- These are applied in the order listed
* This replaces and deprecates the acl_in option.
* Add missing acls.yaml file to the config documentation, which is included
from faucet.yaml but not listed in the docs.
=> Add support for multiple ACLs

faucet/valve.py
When LCAP session goes Up the Valve.lacp_up() method sends a flow_mod DELETE which matches only on in_port, causing the deletion of the flows that intercept LACP messages and send them to controller.    
By using DELETE_STRICT we avoid the deletion of those flows
=> use delete_strict in Valve.lacp_up()

docs/conf.py, docs/requirements.txt
* Fix how we call sphinx-apidoc to work in 1.7
* Lock onto Sphinx 1.7.0 as they seem to have more breaking changes in the pipeline
Fixes #1661
=> Sphinx 1.7 changes how main arguments are parsed.

faucet/config_parser.py, tests/test_config_gauge.py
Instead of providing gauge with a list of faucet.yaml files to
use to read the faucet config, you can now add the faucet
config in the gauge.yaml file
eg.
```
faucet:
dps:
dp1:
dp_id: 1
interfaces:
1:
native_vlan: v1
vlans:
v1:
vid: 1
watchers:
port_stats_poller:
type: 'port_stats'
dps: ['dp1']
db: 'prometheus'
dbs:
prometheus:
type: 'prometheus'
```
This will make it easier to configure gauge to operate from
a separate server to faucet, or to allow gauge to monitor
other non-faucet openflow deployments.
=> Gauge faucet config

adapters/vendors/rabbitmq/Dockerfile.pi
I will need to test this actually runs correctly on pi network on Monday, but it does build. Think it did yesterday but not certain.
=> add a dockerfile for rabbitmq-adapter on raspberry pi

.dockerignore, docker/base/install-faucet.sh, docker/runtests.sh, docs/conf.py, docs/requirements.txt, run-travis-test.sh
#1703 from pyup broke documentation builds because of https://github.com/sphinx-doc/sphinx/issues/4615
Adding doc builds to test suite so this can't happen in future.
I am also reverting #1703 while I wrap my head around the changes to Sphinx.
=> Test documentation builds with test suite

faucet/acl.py, faucet/dp.py, faucet/valve.py, faucet/valve_acl.py, faucet/valve_flood.py, faucet/valve_of.py, tests/faucet_mininet_test_unit.py
dps:
combinatorial_port_flood: True (default)
If False, we use only one flood rule for all ports on a VLAN
(using OpenFlow spec implied behavior, if a rule says in_port=n,output:n,x,y,
packet is sent to x and y only, because OFPP_IN_PORT was not specified).
False is more convenient and may become the default.
=> Make combinatorial_port_flood configurable.

debian/control, debian/faucet.postinst, debian/gauge.postinst, debian/rules
* Makes user/group creation more robust
* Allows users to install packages that are >= 1.7.0
* Remove unwanted /usr/etc directory from python3-faucet package
=> Tidy debian packaging

docker/base/Dockerfile.base-tests
Staging this first since it'll need to propagate through docker hub/cloud before submitting any CL to faucet code proper.
=> Adding test-base dependeny for doing docker-in-docker hosts/testing

docs/configuration.rst
Adds documentation for configuring LLDP.
Also changes the titles of the tables in configuration.rst into a yaml based syntax, that hopefully will be a little easier to understand
=> Lldp documentation

docker-compose-pi.yaml, docker-compose.yaml
A number of docker images will drop back to regular user UIDs when they
start so that they don't run as root which is good. However if this UID
doesn't exist on the system the container won't start.
We will run everything as root for now with the idea that the user
should change the UID to something that exists on their system before
they run docker-compose.
=> Work-around for docker users missing from system.

docs/configuration.rst, faucet/vlan.py, tests/test_vlan.py
- VLAN.faucet_vips now serialises as a string, fixes #1928
- VLAN route config is now correct (fixes #1927)
- Unit tests added for VLAN config
- Documentation updated to match defaults
- VLAN.to_conf() no longer passes Americanised "neighbor" params
- VLAN.check_config() passes through name of missing key
Travis build: https://travis-ci.org/samrussell/faucet/builds/377192081
=> Fix VLAN.to_conf() for routes and faucet_vips

docs/configuration.rst, tests/test_port.py
Travis green - https://travis-ci.org/samrussell/faucet/builds/377565165
No functional changes, adds tests for:
- Port.to_conf()
- Port.vlans()
Docs updated with new fields and updated defaults
=> Add Port unit tests

docs/tutorials.rst
The defaults are correct anyway so let's just remove it to avoid
confusion.
=> Grafana doesn't call this "proxy" anymore.

clib/mininet_test.py, docker/runtests.sh
Somehow this got missed when I did the original docker PR, and so the tests weren't actually being run!  Core problem was that the "hardware" filtering logic wasn't updated, so it was filtering out the tests.
=> Making docker tests actually run

faucet/dp.py, faucet/faucet.py, faucet/port.py, faucet/valve.py, faucet/valve_packet.py, tests/test_valve.py
The protocol will be able to detect wrong cabling, unidirection, and link broken. 
No handling of failures for the moment. 
It takes 2 intervals to detect if a link is working, 3 intervals (configurable) to confirm a link has broken.
The interval can be configured by lldp_beacon send_interval. However, the smallest value can be 5 seconds (the hardcoded interval for send_lldp_beacon service).
Next step to handle failures, including root bridge failure.
=> Implementation of probe protocol for failures on stack

debian/control
If we hard code dependency versions here we need to repackage faucet every time we update a dependency.
=> Make my life easier by not hard coding versions.

faucet/faucet.py, faucet/valve.py, faucet/valve_flood.py, faucet/valves_manager.py
The purpose is to have Valves to update its stack topo upon network events (dp connect, disconect, stack port up/down). No update codes are implemented in this PR.
This prep is for making flood rule calculation dynamic to support root and other failures.
=> Prep methods for handling stack events

docs/vendors/hpe/README_Aruba.rst
This documentation-only update adds a missing command for the HPE
Aruba 5400R, which enables V3-only mode. This is necessary for a
few OpenFlow commands related to pipeline configuration.
=> Update HPE Aruba documentation for 5400R

docker-compose-pi.yaml, docker-compose.yaml
brings influxdb up to 1.6 for both amd64 and arm compose files.  opted away from hypriot's image as it's now archived and hasn't been updated in a year (https://github.com/hypriot/rpi-influxdb).
brings grafana up to the latest for amd64, no newer version for arm yet.
=> updates versions of influxdb and grafana

etc/faucet/cisco_c9k_pipeline.json
- Update the table size to make sure that more tests are passing when using "CiscoC9K" as hardware type
- Update the mask for the "eth_dst" to make sure that the test FaucetStackStringOfDPUntaggedTest is not generating an error when using "CiscoC9K" as hardware type
=> Update the capabilities for the Cisco C9K switch

faucet/vlan.py, tests/unit/test_config.py
allows vlan routes to be configured like org_tlvs as suggested in #1836:
```
routes:
- {ip_gw: '10.0.0.1', ip_dst: '10.99.99.0/24'}
```
=> configuration inconsistency fix #1836

clib/mininet_test_topo.py, faucet/dp.py, faucet/faucet.py, faucet/valve.py, faucet/valve_flood.py, faucet/valves_manager.py, tests/integration/mininet_tests.py, tests/unit/test_valve.py
This is to reflect link-state up/down events on a stack into each DP's stack graph. It works when all DPs are controlled by the same Faucet or events are local (no mechanism to distribute events across Faucet yet).
The updated graph is then used to re-calculate flood/unicast rules.
=> Update stack-graph according to linkstate events

clib/mininet_test_topo.py, tests/integration/mininet_tests.py
**Summary**
In preparation for the Python 3 Mininet merge, these small changes should enable mainline FAUCET to work against my `docker-test-base` changes in https://github.com/lantz/docker-faucet-test-base
An alternative approach would be to move Mininet higher up the docker image stack. We might want to do that anyway? Either way works for me.
Unfortunately the new base image may cause the `sanity` shard to run ~9m slower - see below. :(
**Background**
The root cause is that `pytype` seems to fail with a `not a directory` error when running against python 3 `mininet_tests.py` unless mininet's `.egg`  is unzipped, but doing so in the base image seems to cause `pylint` to explode with a flurry of spurious errors, notably `unbalanced-tuple-unpacking`, which cause `min_pylint.sh` to fail. …
=> pylint fixes to work on new test base image

clib/clib_mininet_test.py, clib/clib_mininet_test_main.py, clib/docker_host.py, clib/mininet_test_base.py, clib/mininet_test_topo.py, clib/mininet_test_util.py, clib/tcpdump_helper.py, docker/localtest.sh, docker/pip_deps.sh, docker/runtests.sh, docker/workarounds.sh, py2-test-requirements.txt, tests/codecheck/pytype.sh, tests/integration/mininet_main.py, tests/integration/mininet_tests.py, tests/run_integration_tests.sh
There are a lot of changes here so you will probably want to review them - I can definitely help with any clarification or additional requested changes.
These changes migrate FAUCET's Mininet-based integration tests to Python 3, removing the requirement for Python 2.
They depend on the test base docker image changes in faucetsdn/docker-test-base#4.
**Overview**
- We install a Python 3-compatible version of Mininet in the base test image (also see below)
- We remove the Python 2 pip dependencies and install the Python 3 versions
- The Mininet-based integration tests are migrated to Python 3
- We invoke the integration tests using Python 2 rather than Python 3
- We run `pytype` invoking it with `-V3.5` on all code
- We invoke a workaround in `docker/workarounds.sh` to compensate for an …
=> Update mininet-based integration tests to python 3

faucet/valve.py
Inheriting from OVSValve cause USE_BARRIERS to be False, but NoviFlow switches require barriers to be used. Inheriting directly from Valve instead
=> NoviFlow Valve must use barriers

faucet/acl.py, faucet/dp.py, faucet/valve.py, faucet/valve_table.py
Move wildcard_table into valve_table.py as it is needed by multiple classes
Also get rid of the NullRyuDatapath object from dp.py, its only needed in acl.py. It probably should be moved elsewhere if there are more uses for it. Possibly conf.py might make sense.
=> Acl config tidy rebase

clib/clib_mininet_test_main.py, clib/clib_mininet_tests.py, clib/docker_host.py, clib/mininet_test_base.py, clib/mininet_test_topo.py, clib/tcpdump_helper.py
changes necessary to allow clib to be imported from an external client under python3.
=> python3 Import cleanup

faucet/faucet_dot1x.py, faucet/faucet_metrics.py, tests/integration/mininet_tests.py
Adds a prometheus success/failure counter.
failure isn't currently used, will require a change to chewie - perhaps a failure_handler
=> Chewie prometheus metrics

faucet/dp.py, faucet/faucet_pipeline.py, faucet/valve.py, faucet/valve_host.py, faucet/valve_route.py, tests/unit/faucet/test_config.py
Progress towards making the eth_src table static
creates an optional classification table before eth_src for directing packets to FIBs, filtering bogons and blocking mac spoofing.
The eth_src table still handles flows for override_output_port (see #2448) and has vlan matches for the controller flows.
This can be configured with the key 'use_classification' in the dp configuration.
=> Static eth src option

faucet/dp.py, faucet/faucet_metadata.py, faucet/faucet_pipeline.py, faucet/tfm_pipeline.py, faucet/valve.py, faucet/valve_host.py, faucet/valve_of.py, faucet/valve_table.py, tests/integration/mininet_tests.py, tests/unit/faucet/fakeoftable.py, tests/unit/faucet/test_config.py, tests/unit/faucet/test_valve.py
A step towards having an egress pipeline. This creates an egress table for unicast traffic.
Instead of outputting directly the eth_dst table will set metadata matching vlan and port and forward the traffic to the egress table, which then matches metadata and vlan and applies vlan actions and outputs the packet.
It has to match vlan so it can use a pop vlan action.
=> Egress table

setup.cfg, tests/codecheck/pytype.sh
Thank you for using pytype! I'm one of the maintainers, and putting your pytype options in setup.cfg would be really helpful for us: it makes it easier to track pytype use cases and figure out what features to prioritize.
=> Move pytype options to setup.cfg.

faucet/faucet.py, faucet/faucet_bgp.py, faucet/valve_route.py, tests/unit/faucet/test_valve.py
Check for an unresolved VLAN at runtime (e.g. when we get a route from BGP that we can't find a VLAN for).
=> Catch exceptions from BGP events.

faucet/dp.py
Sets in python are unordered. The ValveTableConfig compares config objects as strings but the results of converting a set to a string are not deterministic and may depend on PYTHONHASHSEED or other factors. This is not serious, but leads to an unnecessary cold-start.
I made this change in the zof port because I was seeing random test failures for tests that expect a warm-start. Since I’ve made this change, these random test failures have gone away.
I never saw any such failures in the mainline travis tests. I'd have expected the same tests to fail randomly.
=> ValveTableConfig for *_acl tables should use sorted tuples

docs/developer_guide.rst
http://google.github.io/styleguide/pyguide.html was deprecated, updating it to https://github.com/google/styleguide/blob/gh-pages/pyguide.md
=> Updating pystyle URL

clib/mininet_test_base.py, faucet/faucet_metrics.py, faucet/gauge_pollers.py, faucet/gauge_prom.py, faucet/valve.py, tests/integration/mininet_tests.py, tests/unit/faucet/test_valve.py, tests/unit/gauge/test_gauge.py
Fixes https://github.com/faucetsdn/faucet/issues/2597.
=> Add port_description to port Prometheus variables, Gauge uses port not port_name.

clib/clib_mininet_test_main.py, clib/mininet_test_base.py, tests/integration/mininet_tests.py
Fixes https://github.com/faucetsdn/faucet/issues/2624
=> Restrict testing of metadata to OVS (only platform currently supporting it)

.gitlab-ci.yml
Skip additional stages in newer pi-gens.
=> Support pi-gen 2018-11-13-raspbian-stretch.

etc/prometheus/faucet.rules.yml
* Use better names
(https://prometheus.io/docs/practices/rules/#naming-and-aggregation)
* Use *vlan_hosts_learned instead of counting learned_macs
=> Update prometheus rules.

clib/mininet_test_base.py, faucet/valve_flood.py, faucet/valve_of.py, faucet/valve_packet.py, tests/unit/faucet/test_valve.py
Fixes https://github.com/faucetsdn/faucet/issues/2593
=> When flooding to a port that is being mirrored, the mirrored packet must not have a tag if the mirrored port is untagged.

.travis.yml, travis/runtests.sh
clib test suite is failing due to docker-in-docker file system overlaps (can't run another AUFS on top of another AUFS filesystem).
=> Fix travis test runs

faucet/dp.py, faucet/valve_flood.py, tests/integration/mininet_tests.py
Don't send group with same actions but different ID for unicast flooding (may cause hash collision).
Add more port flap tests to stacking.
=> Re-enable groups for stacking.

faucet/faucet_dot1x.py, faucet/port.py
closes [faucetsdn/chewie issue 98](https://github.com/faucetsdn/chewie/issues/98)
=> allow dot1x to run on < 65535 ports per dp.

faucet/valve.py, faucet/valve_flood.py, faucet/valve_host.py, faucet/valve_manager_base.py, faucet/valve_pipeline.py, faucet/valve_route.py, tests/integration/mininet_tests.py, tests/unit/faucet/fakeoftable.py
Make priorities statically determined rather than configurable.
Add unit tests that prevent overlapping flow rules with identical priorities being added to a table.
With new priority structure in place, remove the references to the eth_src table from valve_flood, and use pipeline filters and selects instead.
=> Static priority

.gitlab-ci.yml, gitlab/deploy_deb.sh
Parse debian and ubuntu release CSVs from ``distro-info-data`` to push to faucet packages to all currently supported debian/ubuntu repos.
=> Automatically lookup ubuntu/debian releases for CI package push.

clib/mininet_test_base.py, clib/mininet_test_topo.py, tests/integration/mininet_tests.py
* Protect against _start_faucet() being multiply called (resulting in stranded topology that interferes with the test one).
* Explicitly kill even unhealthy controllers (otherwise an unhealthy controller can remain and interfere with a test)
* FaucetStackStringOfDPExtLoopProtUntaggedTest shouldn't multiply call _start_faucet().
=> test controller restart fixes

faucet/valve.py, faucet/valves_manager.py, tests/unit/faucet/test_valve.py
Internal API change only.
If a controller manages multiple Valves, this allows a event processor to return ofmsgs to be sent to other Valves. For example, when stacking and learning a packet, we could send ofmsgs to all affected Valves learning the host on the very first packet rather than having the Valves learn individually (we can still do so anyway, but this lets us optimize the case where one controller is controlling more than one affected switch).
At the moment nothing takes advantage of the capability, but future features like redundant connected stacks will.
=> Allow valve event processors to return ofmsgs for other Valves.

faucet/valve_flood.py
Prevents unnecessary submarine O(n^2) logic for port checks by culling ports that either aren't physically up, or aren't marked hairpin.  Functionality neutral.
=> Cull unnecessary port logic for flood calculations

clib/mininet_test_base.py, faucet/valve.py, tests/integration/mininet_tests.py
We did not handle the case of a LAG LACP expiry, while remaining op status up (we would continue to use the op up/LACP down link).
Found while fixing hardware tests of LACP in stacks.
=> Fix LACP expiry case.

test-requirements.txt, tests/unit/packaging/test_packaging.py
Fixes the following error:
```
======================================================================
ERROR: test_every_pip_requirement_has_matching_version_in_debian_package (__main__.CheckDebianPackageTestCase)
Test pip requirements versions match debian package dependencies.
----------------------------------------------------------------------
Traceback (most recent call last):
File "/faucet-src/tests/unit/packaging/test_packaging.py", line 64, in setUp
faucet_dpkg = parse_control_fields(deb822_from_string(faucet_dpkg))
File "/usr/local/lib/python3.5/dist-packages/deb_pkg_tools/control.py", line 281, in parse_control_fields
for name, unparsed_value in input_fields.items():
AttributeError: 'Deb822' object has no attribute 'items'
```
=> Packaging unit test fix

docs/architecture.rst, docs/configuration.rst, docs/vendors/ovs/faucet_testing_with_OVS_on_hardware.rst
Figures are more flexible than images and render better in readthedocs.
=> Convert RST images to figures.

docs/developer_guide.rst
Document how to set up a development environment with a Python 3.6+ `venv`, without needing to install PyCharm / use an IDE.  Also document how to build the documentation in the `developer_guide` for convenience :-)   (It is in https://github.com/faucetsdn/faucet/blob/master/docs/README.rst, but that does not end up on https://docs.faucet.nz/...)
=> developer_guide: document env cmdline setup

docs/tutorials/nfv_services.rst
Add example of how to check traffic *is* being mirrored, to help users with debugging if the tutorial does not magically work for them.  (Bro/zeek does not create `dns.log` until it sees DNS traffic, which won't happen if the mirroring is not properly enabled.)
=> tutorial/nfv_services: add tcpdump example

docs/developer_guide.rst
Document additional files that need to be copied to run faucet in a `venv` using the files directly copied out of the git repo.  In particular with the current `faucet.yaml` example supplied, it is necessary to copy `acls.yaml` as well, because `faucet.yaml` includes `acls.yaml`, and without it the config will not load, which will lead to Faucet not starting completely -- with the only errors being in `faucet.log` (the terminal output in the Ryu terminal looks normal).
(It's possibly also worth documenting (a) how to stop the possibly installed `faucet` / `gauge` systemd services -- otherwise the ports are busy -- and the recommended command line for running `faucet` and `gauge` directly, as none of those are immediately obvious.)
=> docs/developer_guide: more files to copy

faucet/faucet_metrics.py, faucet/valve.py
Extend the `faucet_config_table_names` metric to include a comma separated list of next table names in a "next_tables" label, as suggested by @byllyfish in https://github.com/faucetsdn/faucet/issues/2797#issuecomment-464518340.
The `next_tables` value coming off `self.dp.tables.values()` are table IDs, so these are translated to names as part of calculating the return value (and to make those "`next_tables`" values more portable amongst different Faucet runs).
As best I can tell there are no tests on retrieving `faucet_config_table_names` at present (neither `update_config_metrics` nor `aucet_config_table_names` seems mentioned in the tests), and I'm not familiar enough with the Faucet testing framework to know how to create one from scratch (`tests/unit/faucet/test_valve.py` is a 2500+ …
=> valve: add next_tables label to config_table_names

.travis.yml, travis/runtests.sh
Since mininet is not easily install-able by pip we must run pylint inside docker where mininet is pre-installed so that it can pass.
=> Move codechecks back inside docker.

faucet/dp.py, faucet/valve.py, faucet/valve_flood.py, faucet/valve_host.py
Return flag for cache update needed when learning, to remove unnecessary duplicate L2_LEARN events.
=> Remove unnecessary double call to _configure_tables(), reduce unnecessary L2_LEARN events.

faucet/port.py, tests/integration/mininet_tests.py
Fixes https://github.com/faucetsdn/faucet/issues/2726
=> Enable LLDP always for stacking ports.

docs/configuration.rst, faucet/router.py, tests/integration/mininet_tests.py, tests/unit/faucet/test_config.py, tests/unit/faucet/test_valve.py
Allow a router to be configured without top-level VLANs (BGP only).
=> Correct formatting/missing fields for BGP.

images/raspbian/prerun.sh
Only create loop devices if they don't exist.
=> Allow rasbian builds in docker environments where /dev/loop* already exists

faucet/config_parser_util.py, faucet/faucet_metrics.py, faucet/valves_manager.py, tests/unit/faucet/test_valve.py
Report the following information via prometheus stats:
config file hashes as `faucet_config_hash_info{filename="hash",…} 1.0`
config file hash function as `faucet_config_hash_func{algorithm="sha256"} 1.0`
This is intended to make it easier for the [faucet config agent](/faucetsdn/faucetagent) to verify that a config has been accepted, by comparing the hash of a transmitted config file with its hash from `faucet_config_hash_info`. An appropriate hash function implementation may be imported directly from Python's `hashlib` or instantiated using `hashlib.new(algorithm)`.
The `1.0` values are meaningless, but seem to be a prometheus requirement.
I would prefer that the hashes were called `faucet_config_hashes` but the `Info()` class appends `_info` on the name, so `faucet_config_hash_info` …
=> Add faucet_config_hash_info

faucet/config_parser_util.py
CONFIG_HASH doesn't currently need to be global, because it isn't used anywhere else.
=> Remove unneeded CONFIG_HASH global/module variable

faucet/valve_flood.py, tests/integration/mininet_tests.py
One half of a problem I've been tracking down. I have it distilled down to a test, but haven't identified the solution yet. The problem is that the actions generated for stacking ports on a switch set the vlan_pcp=0, which implicitly makes them considered "external" by the receiving switch. It breaks, then, internal --> external communication across the stack.
If you can point me roughly at where in the code this happens, I'd be most appreciative and can fix it up. Otherwise I'll keep on looking... I just haven't found where the rule actions are constructed yet...
=> packets on stacking ports are marked as external_loop_protect (vlan_pcp=0) even when they're not.

faucet/faucet_dot1x.py, faucet/valve.py, faucet/valve_acl.py, tests/integration/mininet_tests.py
BUGFIX: Remove Default ACL when Authenticated Correctly
Simplify the logging of events inside the dot1x module.
Remove acl_manager dependency from faucet_dot1x.py module
Enforce valve dot1x functions only require port numbers not 'dot1x_port' type.
Remove flow building from handler functions and split into reusable components.
Rename internal variables to conform to Python standard.
=> Refactor faucet_dot1x.py

faucet/faucet.py, faucet/faucet_metrics.py, faucet/valves_manager.py, tests/unit/faucet/test_valve.py
The `faucet_config_errors` and `faucet_config_reload_requests` prometheus statistics can be used to indicate whether FAUCET has received a reload request and whether the last configuration was loaded correctly. This is what the prototype [FAUCET config agent](/lantz/faucetagent) does. (The plan is also to report and use a config hash such as `faucet_config_sha256`.)
However, this only indicates that the FAUCET state has been updated – what about the datapath state? Prior to version 1.5, OpenFlow provided no guarantees, but OpenFlow 1.5+ actually mandates that state must be committed to the datapath before a barrier reply.
So, in theory, we could keep track of barrier replies, but:
1. FAUCET doesn't use barriers with all switches (maybe it should?)
2. FAUCET is intended to work with …
=> faucet_config_applied: report the fraction of datapaths that we have tried to apply the config to

faucet/faucet_metrics.py, faucet/valves_manager.py, tests/unit/faucet/test_valve.py
The new format is:
`faucet_config_hash_info{config_files='file1,file2,file3', hashes='hash1,hash2,hash3'} 1.0`
This should enable us to fix faucetsdn/faucetagent#12 using faucetsdn/faucetagent#13
=> Update faucet_config_hash_info label format for compatibility with faucetagent

README.rst, docs/vendors/cisco/README_Cisco.rst
Fix broken Zodiac GX product page and Cisco C9300-48P-A datasheet links.
=> Fix two broken switch vendor URLs in the docs

clib/mininet_test_base.py, clib/mininet_test_topo.py, hw_switch_config.yaml
By default, when the faucet test suite is running, it will use the IPv4 address of the CPN interface to start
the Faucet and the Gauge controllers.
By adding a new field to the hw_switch_config.yaml, the test code could use the IPv6 address of
the CPU interface instead of the IPv4 address.
The changes should be backward compatible. The field is optional and if not present, this means use the IPv4 address of the CPN interface.
A new member "controller_ipv6" is added to the class BaseFAUCET (along with the member "controller_intf"). This member will be initialized with the value set in the configuration file hw_switch_config.yaml
=> Add a new option to the hw_switch_config.yaml to be able to use the IPv6 of the CPN interface

.gitlab-ci.yml
pi-gen 2019-04-08-raspbian-stretch (#2909) doesn't build for us right now so downgrade while we try work out what the problem is.
=> Downgrade pi-gen to 2018-11-13-raspbian-stretch.

docs/vendors/cisco/README_Cisco.rst
Based on release notes, it seems public IOS XE releases now support FAUCET. The Cisco vendor doc still suggests FAUCET support is beta, and points users to an email address to request beta images.
This PR updates the documentation to reference relevant release notes and the config guide for OpenFlow, but does not resolve the beta/release ambiguity.
@creneCSCO could you please verify the current support status?
=> Add section on non-beta Cisco IOS XE versions

clib/clib_mininet_test_main.py, clib/clib_mininet_tests.py, clib/mininet_test_base.py, clib/mininet_test_topo.py, tests/integration/mininet_tests.py
Add an option (`-p`) to the integration tests to specify OvS port numbers, either explicitly or randomly, defaulting to `random`.
We generate a list of random port numbers (`port_base`) which is extended as needed and used for allocating OvS port numbers in `FaucetSwitchTopo` and its subclass `FaucetStringOfDPSwitchTopo`.
The test classes call `FaucetTestBase.create_port_map(dpid)` which reads `self.topo` to create `port_maps[dpid]` and `port_map`, which is a shortcut for `port_maps[self.dpid]`.
Each port map (e.g. `port_maps[dpid]['port_1']`) tells you the actual OvS/OpenFlow port number for `port_n` on `dpid`, allowing tests to use virtual port identifiers (`port_1`...) rather than fixed numbers.
At the moment I am restarting the allocation for each switch, and the switch-to-switch …
=> Support for port remapping/randomization

faucet/dp.py, faucet/port.py, faucet/valve.py, tests/integration/mininet_tests.py
Fixes problem where the dyn_ state of ports is not maintained on reconfiguration. This manifests itself as part of lacp state management, which is where the triggering test resides.
=> Clone dyn_ port state on reconfigure

docker/runtests.sh, docs/testing.rst
* Recommend using separate cache directory (rather than the user one)
* Remove need to prime the cache before use
=> Make pip cache easier to use for docker test runs.

faucet/valve_ryuapp.py
and thread schedule jitter can be a float for better load distribution.
Fixes https://github.com/faucetsdn/faucet/issues/2978
Fixes https://github.com/faucetsdn/faucet/issues/2997.
=> self.threads continually grows leading to high CPU.

faucet/port.py, faucet/valve.py
Changing the way age is calculated so that faucet relies on the time it last responded to a LACP packet rather than when it was last received.
=> Fixing LACP response

clib/mininet_test_topo.py, docker/pip_deps.sh, tests/integration/mininet_tests.py, tests/unit/faucet/test_topo.py
We add some introspection facilities to the test topology so that `get_config()` can use its wiring directly rather recomputing its own version.
=> Simplify get_config() in mininet_tests.py

docs/vendors/northboundnetworks/conf-zodiac.sh
The values in the patch are the ZodiacFX defaults, so these
will need to be adjusted for the deployed controller network.
=> conf-zodiac.sh: set Zodiac and OF controller network details

faucet/valve_flood.py, tests/integration/mininet_tests.py
* Broadcast loop check added to all stacking test cases.
* Ensure a possibly stale port-specific rule will be deleted when combinatorial port flood mode is not in use
* Sure traffic on a down stack link is explicitly blocked to remove the possibility of a brief loop between the port coming up and flows hitting the default rule, and FAUCET reacting to the port up message and sending the right flows.
Fixes https://github.com/faucetsdn/faucet/issues/3013
=> Stack flooding fixes

clib/clib_mininet_test_main.py, clib/mininet_test_base.py, clib/mininet_test_topo.py, docker/runtests.sh, tests/integration/mininet_tests.py, tests/unit/clib/test_topo.py
Experimenting with a simpler and more incremental approach.
Adds a parameter `--order 0,1,2,3 | random`
to the integration tests to allow random or predetermined ordering for `port_map`.
By default, it is `random` which uses a random shuffle of `0,1,2,3`.
This allows tests to exercise hardware or software switch ports in a non-canonical order.
=> Allow fixed or random ordering for port_map

setup.cfg
This PR removes the need for preversioning after each release.
=> If we don't specify an explict version PBR will calculate from git tags.

faucet/faucet_dot1x.py, faucet/valve.py, faucet/valve_flood.py, faucet/valve_host.py, faucet/valve_manager_base.py
* Most knowledge about how the flood table is updated moved to the flood manager (introduced warm reconfig call update_vlan() to allow future further optimization)
* Host state handling (was incomplete anyway) moved from 8021X to host manager.
* pylint cleanup of unused LACP args
=> table manager API cleanup for flooding and 8021X

clib/clib_mininet_test_main.py
It seems that we should be able to run `FaucetSanityTest` standalone, and I think this should enable it.
Closes #3086
=> Allow FaucetSanityTest to be run standalone

faucet/dp.py, faucet/faucet.py, faucet/faucet_dot1x.py, faucet/valve.py, tests/integration/mininet_tests.py, tests/unit/faucet/test_config.py, tests/unit/faucet/test_valve.py
Add Kill On Exception flag to API for Chewie
BUGFIX: Enforce output_only restraint on nfv_sw_port
Add tests for restraint
Change Mininet dot1x tests to use restraint
Remove Invalid Usage of NFV Port from 8021XPortFlapTest and 8021XVLANTest
=> Testing kill on exception

tests/integration/mininet_tests.py
The first part of the fix will indicate that the test "FaucetUntaggedEgressACLTest" is using metadata. As metadata is not supported on Cisco C9K switch, this test will not get executed for this platform.
The second part of the fix is increasing the flood table size to 64 flows. This will allow the tests "FaucetTunnelSameDpTest" and "FaucetTunnelTest" to run successfully. Indeed those two tests needs to install 34 flows in the flood table but by default the flood table is accepting as most 32 flows.
=> - Fix some tests to avoid some failures on Cisco C9K

tests/integration/mininet_tests.py
Move Dot1x Event checks from teardown method to end of tests
=> Remove Dot1x Event Checks from 8021x Teardown

test-requirements.txt, tests/integration/mininet_tests.py
Allows us to use the latest exabgp again.
=> Latest exabgp strictly verifies routes can't be hosts.

tests/codecheck/pytype.sh
Use that rather that rather than GNU parallel - much faster since running under GNU parallel can have a run time of 30m!
Reduces run time to about 7m.
=> Later pytype has its own parallel run capability. 

test-requirements.txt
Lock scapy to 2.4.2 so @renovatebot will tell us when 2.4.3 gets released
=> Lock scapy to 2.4.2.

clib/mininet_test_base.py, tests/integration/mininet_tests.py
First we change the DPID to something incorrect and then wait for FAUCET to disconnect from the switch several times.
Then we restore the correct DPID, reload the config, and verify that `untagged_test()` still works.
Notes: 
Initially I was dissatisfied with this approach for a couple of reasons, but now I think maybe it isn't so bad. Most of the delay seems to be from waiting for the switch to reconnect and for performing the connectivity test. Even if we did this in another way, we would still have to wait for the switch to reconnect, which is a switch configuration, and we would still want to run the connectivity test. We could try a simpler/faster test however (e.g. just do the ping test.)
=> Verify that switch works after several disconnections

clib/mininet_test_base.py, clib/mininet_test_topo.py, faucet/dp.py, faucet/valve.py, faucet/valve_flood.py, faucet/valve_host.py, faucet/valve_route.py, faucet/valves_manager.py, faucet/vlan.py, tests/integration/mininet_tests.py, tests/unit/clib/test_topo.py, tests/unit/faucet/test_check_config.py, tests/unit/faucet/test_config.py, tests/unit/faucet/test_valve.py
- Enable the ability to use stacking with inter-VLAN routing (#2672 ).
- drop_spoofed_faucet_mac should be set to false to allow a routed packet enter the eth_src table on another switch.
- A valve receiving packets will call other valves in the stack to also learn the host.
=> Enable inter-VLAN routing with stacking

clib/mininet_test_base.py, tests/integration/mininet_tests.py
We generate some questionable flow mods and send them to the switch.
Then we verify that hosts can still ping each other.
This seems to result in some (presumably correct) OpenFlow errors from the switch. OvS in particular (on my HW testbed) doesn't seem to like the MPLS actions. On the other hand it seems perfectly OK with bogus port and table numbers.
Unfortunately posting via `ofctl` is very slow, but it does seem to work. For that reason, we currently only send 10 flow mods, but we could send more.
Some things to think about:
- Do we want to try bogus flow adds/deletes as well as modify operations?
- Do we want to try to generate specific errors for TFM switches?
- Is this valuable? Are there other bad OF messages we might want to add?
=> FaucetBadFlowModTest: Send bad flow mods to switch

faucet/check_faucet_config.py, faucet/config_parser.py, faucet/dp.py, faucet/faucet.py, faucet/faucet_metrics.py, faucet/faucet_pipeline.py, faucet/valve.py, faucet/valve_flood.py, faucet/valve_host.py, faucet/valve_of.py, faucet/valve_packet.py, faucet/valve_pipeline.py, faucet/valve_table.py, faucet/valves_manager.py, faucet/vlan.py, tests/integration/mininet_tests.py, tests/unit/faucet/test_config.py, tests/unit/faucet/test_valve.py
* Add support for multiple stack roots (FAUCET will pick one, only the active one will use any LACP bundle)
* Clarify use of external forwarding requested field, avoid PCP 1, remove unneeded TFM request to vlan_pcp on eth_src.
=> Simple stack root redundancy

tests/integration/mininet_tests.py
OpenFlow switches should reject match fields which are inconsistent or erroneous for a particular protocol, or which are missing key pieces of information (e.g. the transport protocol for an L4 port match action.)
We add some non-compliant matches which should generate `OFPET_BAD_MATCH` errors from the switch (and not break forwarding!).
=> Add bad matches to FaucetBadFlowModTest

clib/clib_mininet_test_main.py, docker/runtests.sh
Also change default mininet logging level to `warning`.
We should also probably review the usage of loggingroutines (e.g. `error()`) in the tests.
=> Add --loglevel option to set mininet log level

clib/clib_mininet_test_main.py, clib/mininet_test_base.py, clib/mininet_test_topo.py, tests/integration/mininet_tests.py
We extend `FaucetUntaggedTest` to allow it to work with  more than 4 ports, and add `Faucet32PortTest` and  `Faucet48PortTest`.
The 48p test works locally but seems to be   slow/unreliable on travis so we just run the 32p test for now.
I also rewrote `_attach_physical_switch()` to clarify it a bit and make sure that it works properly with more than 4 ports.
Possibly blocked by #3191
=> Test up to 48 ports

clib/clib_mininet_test_main.py, docker/runtests.sh
Add a `--profile` option to report elapsed real (wall clock) time for functions, sorted by
cumulative time spent. This may help to identify opportunities for speeding up the tests, for
example reducing unnecessary `sleep()` calls.
=> Add a profiling option to the integration tests

docs/configuration.rst, faucet/dp.py, faucet/faucet_pipeline.py, faucet/port.py, faucet/valve.py, faucet/valve_flood.py, faucet/vlan.py, tests/integration/mininet_tests.py, tests/unit/faucet/test_valve.py
Fixes https://github.com/faucetsdn/faucet/issues/1454.
=> Restrict a port to sending ARP/IPv6 ND broadcasts only. 

gitlab/deploy_deb.sh
* Don't use gitlab web interface (which is rate limited) to download CSVs.
* Allow script to run interactively better by disconnecting stdin.
=> Improve deploy_deb.sh.

docs/configuration.rst, faucet/check_faucet_config.py, faucet/config_parser.py, faucet/config_parser_util.py, faucet/faucet.py, faucet/valve_util.py, faucet/valves_manager.py, tests/unit/faucet/test_config.py, tests/unit/faucet/test_valve_config.py, tests/unit/faucet/valve_test_lib.py
Fixes https://github.com/faucetsdn/faucet/issues/2719.
Setting FAUCET_CONFIG_AUTO_REVERT enables the feature.
=> Allow FAUCET to optionally, automatically revert bad configs itself

faucet/valve_of.py
This will stop global METER deletes being discarded
when DP's connect
=> Mark global METER deletes as 'deleteglobal' kind

docs/configuration.rst, faucet/dp.py, tests/unit/faucet/test_valve.py
Allow scaling of port scale tables.
=> Enable table size to override estimate always.

tests/unit/faucet/fakeoftable.py, tests/unit/faucet/test_valve.py, tests/unit/faucet/test_valve_config.py, tests/unit/faucet/test_valve_stack.py, tests/unit/faucet/valve_test_lib.py
Use a mock time provider rather than time.time(), and fix some problems with fake table handling (installing flows from wrong table), and refactor loop topology definition.
This is all "functionality neutral" and doesn't change any existing test behavior, or add any new test functionality.
I discovered all this while working through PR https://github.com/faucetsdn/faucet/pull/3261 -- and once this is resolved, I'll update that to match.
=> Faucet unit test fixup

tests/integration/mininet_tests.py
Otherwise, test fails by hitting a *key error*.
=> test_passthrough accesses wrong dp for lacp

tests/integration/mininet_tests.py
Some hardware devices won't cope with timers < 10 seconds so increase timers.
=> Increase timers so test passes on hardware.

docs/tutorials/stacking.rst
Remove the dummy ports I was using to workaround #3272 which got fixed by #3309
=> Remove workaround for github issue #3272.

clib/mininet_test_base.py, etc/faucet/gauge.yaml, faucet/watcher.py, faucet/watcher_conf.py, tests/unit/faucet/fakeoftable.py, tests/unit/gauge/test_gauge.py
This branch failed travis on my github and on my desktop, but passed when I accidentally pushed to my old github https://github.com/KitL/faucet/runs/264929690
The failure isnt obviously connected with the changes I have made.
So I'm not sure what is going on with it at the moment, but I figured if I make the PR I will get a known good environment for running the tests.
This is a breaking change.
The old format involved severe hackiness to make it manageable
This format instead will just dump each OFStatsReply message
straight into its own file.
The filename will be {datapath_name}-flowtable-{timestamp}.json
The directory these files will be stored can be configured using
the "path" key in the configuration for a text db
The tests and the default gauge.yaml have been changed accordingly …
=> Change the output format for gauge text flow table stats

faucet/dp.py, faucet/port.py, faucet/valve.py, tests/unit/faucet/test_valve_stack.py
Allow a multi root stack to aggregate its LACP ports to non MC-LAG devices.
Normally Faucet sets one port (on the root stack switch) to Collecting and Distributing (Active) and the others to not Collecting and not Distributing (Standby). This works fine with MC-LAG enabled devices where different devices establish aggregation via multiple ports as it they were one device. However, enabling this for non MC-LAG devices is just a matter of overriding the need to Standby. This knob forces all LACP configured ports to Collecting and Distributing.
Because enabled ports will all state that they desire to collect traffic, they will receive traffic, however this traffic will always be dropped on non root stack switch.
=> Add lacp_collect_and_distribute port config option

faucet/port.py, faucet/valve.py, tests/integration/mininet_tests.py, tests/unit/faucet/test_valve_stack.py, tests/unit/faucet/valve_test_lib.py
Expose different states for different stack-down conditions (miscabling vs. timeout)
=> Clean up LLDP state & notification

clib/mininet_test_base.py, faucet/dp.py, faucet/faucet_event.py, faucet/valve.py, faucet/valves_manager.py, tests/integration/mininet_tests.py
Adding STACK_TOPO_CHANGE and LAG_CHANGE events to dump stack topology graph obj and LAG status info to event socket. Events will be consumed by forch to show current faucet network status.
=> Add additional events for system monitoring

tests/unit/faucet/fakeoftable.py
Allows using fakeoftable from the CLI to print a flow table into a human readable format, or to probe for what actions are applied to a packet.
It currently doesnt really handle groups at all. It can tell you what groups are applied but doesnt tell you what the groups do. We would need to add monitoring of the group table in gauge for that to work.
Here are examples:
(faucet)chrislorier@kit:~/faucet/tests/unit/faucet$ python fakeoftable.py probe -f ~/ft_1.json -p '{"in_port": 1, "vlan_vid": 1000, "eth_dst": "ff:ff:ff:ff:ff:ff", "eth_src": "00:00:00:00:00:01"}'
{'vlan_vid': 5096, 'eth_src': '00:00:00:00:00:01', 'eth_dst': 'ff:ff:ff:ff:ff:ff', 'in_port': 1}
OFPInstructionGotoTable(len=8,table_id=1,type=1)
OFPInstructionGotoTable(len=8,table_id=2,type=1) …
=> Cli fakeoftable

faucet/conf.py, faucet/router.py, tests/integration/mininet_tests.py
To create a 'hash'able Router class, the PyTricia
tree needs to be unrolled (the 'id()' based 'repr'
does not allow for comparison of logically equivalentr
instances)
This change now results in some previous tests that
reported unnecessary 'cold' restarts, now reporting
'warm' restarts instead.
=> router.py: Add 'repr' implementation for vip_map_by_ipv (#3347)

faucet/faucet_metrics.py, faucet/valve.py, tests/unit/faucet/test_valve_stack.py
Includes modifying a stack redundancy test to check for the validity of the varz.
=> Adding a varz to track shortest root path port for every DP

docker/runtests.sh, docs/testing.rst
* Support long-form argument names
* Add support for reading arguments from ARGV
* Don't pass arguments meant for just runtests.sh onto mininet scripts
fixes #3364
=> Make runtests.sh argument parsing more robust.

faucet/valve.py, faucet/valve_flood.py, faucet/valve_host.py, tests/integration/mininet_tests.py
See also: https://github.com/faucetsdn/faucet/issues/3333
=> Fix missing VLAN learn rule after warm start, don't learn host on external port if another stack DP has learned it locally.

faucet/gauge_pollers.py, faucet/gauge_prom.py, tests/integration/mininet_tests.py, tests/unit/gauge/test_gauge.py
Not sure why it's not showing up in influx, which is used as a test comparison... I'm missing something here I think -- looking for some hints.
=> Add txerror to prom

AUTHORS, docs/tutorials/routing.rst, docs/tutorials/stacking.rst
Hello,
this fixes to issues in the tutorial: BGP syntax changed for version 1.9 and it was once forgotten to
mention to reload faucet after a configuration change. I build the docs successfully.
Cheers,
Thomas
=> Fix issues in tutorial due to changed BGP syntax in 1.9

clib/mininet_test_watcher.py, tests/tolerance/mininet_main.py, tests/tolerance/mininet_tests.py
Dynamically add in tests for all (connected, (probably) non-isomorphic) topologies on 2-7 nodes, ~1000 topologies overall.
Travis only tests 2-4 node topologies.
=> Test all topologies

faucet/valve.py
Can interfere with redundant controllers.
=> Don't do a delete all on disconnect.

clib/mininet_test_topo_generator.py, docs/tutorials/stacking.rst, faucet/dp.py, faucet/valve.py, tests/integration/mininet_multidp_tests.py
L2 could fail when a transit switch did not know the right VLANs
Fixes #3383
=> Allow stack switches to know all VLANs

docs/configuration.rst, docs/tutorials/first_time.rst, faucet/dp.py, faucet/valve.py, faucet/valve_of.py, tests/fuzzer/dict/config.dict, tests/unit/faucet/valve_test_lib.py
Current faucet doesn't clear all types of meters when doing cold restart. (only deletes DP meters).
Also added slowpath meter as per OFv1.3 specification.
=> delete all meters on cold start and add slowpath meter

faucet/gauge.py, faucet/gauge_pollers.py, faucet/gauge_prom.py, tests/unit/gauge/test_gauge.py
Prevents the internal poller update() from shadowing the one in GaugePoller which sets the response as received. This PR will fix spurious "no response" log messages showing up despite data being actually logged.
Seems to be a problem since f0bd3b982fe6d439cef4b2d658654ac56a9a31aa
=> update() -> _update() for prom pollers

faucet/conf.py, faucet/port.py, faucet/valve.py, tests/integration/mininet_multidp_tests.py, tests/unit/faucet/test_config.py, tests/unit/faucet/test_port.py, tests/unit/faucet/test_valve.py, tests/unit/faucet/test_valve_stack.py
- LACP actor & port selection states on yet to be configured/unconfigured ports will default to `LACP_ACTOR_NOTCONFIGURED` & `LACP_PORT_NOTCONFIGURED` respectively.
- Upon a port down, actor state will change to `LACP_ACTOR_NONE`.
- Upon cold starting a port, actor state & port selection state will revert back to `LACP_ACTOR_NOTCONFIGURED` & `LACP_PORT_NOTCONFIGURED` respectively.
- `LACP_ACTOR_NOACT` renamed to `LACP_ACTOR_NOSYNC`.
- Added `lacp_unselected`, `lacp_selected` & `lacp_standby` config options to force a port's LACP selection state.
=> Modify LACP state machine

tests/tolerance/mininet_tests.py
Apart from being yet another check that the test suite is correct, it also reduces the test suite's load sensitivity (by not trying to verify connectivity until we are certain the controller knows the desired link state).
=> When adding a link fault, check that the controller sees the same fault on the same link

docs/configuration.rst, tests/fuzzer/dict/config.dict
Undocument drop_bpdu which was removed in https://github.com/faucetsdn/faucet/commit/a6d781e32b4fcc56fccfb9a77c3f63780873273b
=> drop_bpdu no longer exists.

docs/configuration.rst, docs/tutorials/acls.rst, faucet/acl.py, faucet/dp.py, faucet/port.py, faucet/valve.py, faucet/valve_acl.py, tests/integration/mininet_multidp_tests.py, tests/integration/mininet_tests.py, tests/unit/faucet/test_config.py, tests/unit/faucet/test_valve_stack.py, tests/unit/faucet/valve_test_lib.py
Allow ordered ACL output actions as mentioned in #3468 (Closes #3468).
```
acls:
ordered_acl:
- rule:
dl_vlan: 100
actions:
output:
- port: 2
- pop_vlans: 1
- port: 3
```
Fix #3389 
Allow defining a tunnel without requiring a VLAN, Faucet will pick an unused VID that is larger than the configured VIDs (Closes #3314).
e.g.: The following config will create a tunnel that will be encapsulated with VID 101
```
vlans:
vlans:
vlan100:
vid: 100
acls:
tunnel-to-host1:
- rule:
actions:
output:
tunnel:
dp: sw1
port: 1
```
Tunnel ACLs will pop off the encapsulation after the output action so rules can now be applied after a tunnel action. e.g.: The output to port 6 will not have the tunnel VID applied
```
acls:
tunnel_acl:
- rule:
ip_proto: 1
dl_type: 0x0800
actions:
output:
- port: 5
- tunnel: {dp: …
```
=> Ordered ACL output actions

clib/clib_mininet_test_main.py, clib/mininet_test_base.py, clib/mininet_test_base_topo.py, clib/mininet_test_topo.py
Specify a port number or 'random'. Random chooses a number from 1 to 10. Default is set to 'random'.
e.g:
```
sudo docker run --privileged --rm --net=host --cap-add=NET_ADMIN \
-e FAUCET_TESTS="--port 25" \
-ti faucet/tests
```
=> Add option for integration test start port

faucet/port.py, tests/unit/faucet/test_port.py, tests/unit/faucet/test_valve_stack.py
`lacp_standby` forces port state to `STANDBY` when not `SELECTED`
superseeds #3500
=> Prioritise selected link over standby

faucet/valve_of.py, tests/unit/faucet/test_valve_stack.py
Fixes #3495 
When re-ordering ofmsgs we were removing all the delete-ofmsgs if there existed any global delete. This was removing our groupdel from the ofmsgs list.
Now removes delete-ofmsgs that have a global delete of the same type.
=> Only remove delete ofmsgs that have a global delete of the same type

faucet/faucet_metrics.py, faucet/valve.py, tests/unit/faucet/test_valve_stack.py
We currently monitor the LACP state of a port. The PR adds an additional metric that exposes the port role as well.
=> Add varz port_lacp_role to monitor LACP role

clib/mininet_test_base_topo.py, tests/integration/mininet_tests.py
Linux occasionally returns a non-zero lacp churn metric during a test suite run.
I'm not entirely sure what metric means, but I think we can safely ignore it.
=> Ignore LACP churn metric.

clib/mininet_test_base.py
Solves a test flake in FaucetUntaggedIPv4RouteTests.
For FaucetUntaggedIPv4RouteTests, we have a pattern where we:
1. ping from host to faucet vip
2. check faucet learned the host route (/32)
Faucet currently only learns host routes from ARP packets (we trigger this in the test suite with one_ipv4_controller_ping()), however you can occasionally run into a situation where a test host has a primed ARP cache when one_ipv4_controller_ping() is run which means only an ICMP request message is sent to the faucet VIP (no ARP message so the host route isn't installed).
This change ensures the ARP packet is generated by explicitly clearning the ARP cache on the test host before one_ipv4_controller_ping() is run.
superseeds #3525
=> Flush arp cache before pinging faucet VIP.

docker-compose-pi.yaml
This is really a stop gap until `docker-compose-pi.yaml` can be fully removed when the remaining faucet/gauge/etc images push to docker hub with multi-arch.  This also removes the need for the Dockerfile.pi in https://github.com/faucetsdn/docker-prometheus.git
=> images now have multi-arch for x86_64/arm

faucet/valve.py, tests/integration/mininet_multidp_tests.py
The content of STACK_TOPO_CHANGE was changed recently as part of [fec52f](https://github.com/faucetsdn/faucet/commit/fec52f905b12046b95e32bdf5cc4fc859485ab31) However, the MultiGraph() object is not serializable and hence the STACK_TOPO_CHANGE event is emitted with 'graph' field empty. 
Currently, faucet tests dont check for the content of an emitted event. Please let me know if the tests are needed.
=> Revert back to serialisable form of stack graph

faucet/valve_of.py, tests/unit/faucet/fakeoftable.py, tests/unit/faucet/test_valve_config.py, tests/unit/faucet/test_valve_stack.py, tests/unit/faucet/valve_test_lib.py
Also add tests that flows revert to pre-change state when a config change is made and reverted.
=> Make flow reordering consistent between different python versions

test-requirements.txt
Pylint 2.5+ gives `faucet/valve_switch.py` a negative score for some reason which breaks `min_pylint.sh`
```
pylint /faucet-src/faucet/valve_switch.py
************* Module faucet.valve_switch
faucet/valve_switch.py:65:11: E1120: No value for argument 'stack_ports' in constructor call (no-value-for-parameter)
faucet/valve_switch.py:65:11: E1120: No value for argument 'dp_shortest_path_to_root' in constructor call (no-value-for-parameter)
faucet/valve_switch.py:65:11: E1120: No value for argument 'shortest_path_port' in constructor call (no-value-for-parameter)
faucet/valve_switch.py:65:11: E1120: No value for argument 'is_stack_root' in constructor call (no-value-for-parameter)
faucet/valve_switch.py:65:11: E1120: No value for argument 'is_stack_root_candidate' in constructor call …
```
=> Downgrade pylint.

faucet/dp.py, faucet/faucet_metrics.py, faucet/port.py, faucet/valve.py, tests/integration/mininet_tests.py
Currently, we set the lacp port id to the DP port number. However, this sends the same value on separate links if the same ports are configured. The PR combines the DP ID and the port number to generate a port ID that is used as the LACP port number instead. 
The PR has a test that tests for the LACP port num using the same algorithm.
=> Use a calculated combination of dp_id and port number for lacp port num instead of the port number

faucet/valve.py, tests/integration/mininet_multidp_tests.py
The PR helps track the lacp port role in addition to actor state in events. It modifies an existing check for the existence of the LAG_CHANGE event in the event logs to check for the presence of actor state and port role as well.
=> Add lacp port role to LAG_CHANGE event in addition to actor state

clib/config_generator.py, clib/mininet_test_base.py, clib/mininet_test_base_topo.py, faucet/conf.py, faucet/dp.py, faucet/port.py, faucet/valve.py, tests/integration/mininet_multidp_tests.py, tests/unit/faucet/test_valve_stack.py, tests/unit/faucet/valve_test_lib.py
Fix #3523
- Stop stack ports from always being detected as changed. This keeps stack ports up during warm starts.
- Restart stack ports on a topology change, topology changes detected with a stack graph hash.
=> Don't take stack ports down when warm starting

faucet/valve.py
If someone configures dot1x for a datapath but doesn't enable it on any interfaces on that datapath faucet will crash.
fixes #3566
=> Fix dot1x enable check.

debian/control, requirements.txt, tests/unit/packaging/test_packaging.py
Transitional requirement msgpack-python no longer required.
Allow msgpack from 0.4.6 onwards (ubuntu xenial), but don't allow msgpack 1.0.0 due to ryu not supporting it yet.
=> Tidy up msgpack requirement.

tests/unit/faucet/valve_test_lib.py
This impacts runtime performance for large configs.
=> Prevent possible regressions where flow generators (e.g. flood rules)  could generate a lot of duplicate flows.

docs/Makefile, faucet/valve.py
Fixes silently ignored things like:
/home/travis/build/anarkiwi/faucet/faucet/valve.py:docstring of faucet.valve.Valve.get_lacp_dpid_nomination:3: WARNING: Unexpected indentation.
/home/travis/build/anarkiwi/faucet/faucet/valve.py:docstring of faucet.valve.Valve.get_lacp_dpid_nomination:6: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/travis/build/anarkiwi/faucet/faucet/valve.py:docstring of faucet.valve.Valve.lacp_enable_forwarding:3: WARNING: Definition list ends without a blank line; unexpected unindent.
/home/travis/build/anarkiwi/faucet/faucet/valve.py:docstring of faucet.valve.Valve.lacp_update:4: WARNING: Definition list ends without a blank line; unexpected unindent.
=> Make sphinx warnings, errors and fix errors.

.travis.yml, travis/runtests.sh
Ubuntu 20.04 uses python3.8, we should make sure faucet works with that version.
Also makes pytype and pylint run outside of docker.
fixes #2655
=> Run unit tests on python3.8.

debian/rules, docker/install-faucet.sh
#3597 broke package builds as our build environment doesn't have mininet installed.
Temporarily disable unit tests on package builds until we get the problem fixed.
=> Temporarily disable unit tests on package builds.

debian/rules, docker/install-faucet.sh
Reverts temporary work around faucetsdn/faucet#3603 now that #3606 fixes the actual issue.
=> Revert "Temporarily disable unit tests on package builds."

faucet/config_parser.py, faucet/valve_switch.py, faucet/valve_switch_stack.py, tests/codecheck/pytype.sh
Unfortunately no -j "auto" option, so using 2 as a default.
Before (no -j):
faucet@faucet:~/faucet$ PYTHONPATH=. time ./tests/codecheck/pytype.sh
Using /usr/local/bin/pytype (header #!/usr/bin/python3)
Computing dependencies
Analyzing 87 sources with 1 local dependencies
ninja: Entering directory `/var/tmp/tmp.GaQQHv4nCQ/{/}'
[88/88] check tests.fuzzer.display_packet_crash
Success: no errors found
141.93user 2.83system 2:24.06elapsed 100%CPU (0avgtext+0avgdata 210224maxresident)k
0inputs+1824outputs (0major+1020565minor)pagefaults 0swaps
After (-j 2):
faucet@faucet:~/faucet$ PYTHONPATH=. time ./tests/codecheck/pytype.sh
Using /usr/local/bin/pytype (header #!/usr/bin/python3)
Computing dependencies
Analyzing 87 sources with 1 local dependencies
ninja: Entering directory …
=> Run parallel pytype for ~50% reduction in worst case run time.

setup.cfg
Actually make the per-python pytype runners added in #3570 work.
=> Don't hardcode python_version for pytype.

clib/valve_test_lib.py, faucet/dp.py, faucet/faucet_dot1x.py, faucet/faucet_event.py, faucet/fctl.py, faucet/prom_client.py, faucet/valve.py, faucet/vlan.py
=> Some TODO cleanup

faucet/valve.py, tests/unit/faucet/test_valve_stack.py
Currently, we only update varz and send out an event when the port state is changed. However, this leaves out corner cases during controller failover and in some cases, LACP link failover, where the role is updated internally but isn't reflected in the monitoring varz. 
The PR also updates test_nominated_dpid_port_selection to check for the varz after calling lacp_update instead of explicitly calling _reset_lacp_status.
=> Update lacp varz when LACP port role is updated

faucet/gauge.py, faucet/gauge_prom.py
This ensures all port descriptions, etc are current. As variable values are asserted by OpenFlow replies from the datapath, no data is actually lost, though if Prometheus polls after a config reload but before a regularly scheduled poll, it will not see updated variables for that poll.
=> Reregister all variables on config reload.

clib/fakeoftable.py, clib/valve_test_lib.py, tests/unit/faucet/test_valve_config.py, tests/unit/faucet/test_valve_stack.py
I had to generate the offset ofmsgs from the original (before reorganizing and optimizing) ofmsgs due to the prepared ofmsgs flow structure.
=> Add unit test redundant ofmsgs offset check

clib/fakeoftable.py, clib/valve_test_lib.py, docs/configuration.rst, faucet/conf.py, faucet/dp.py, faucet/faucet.py, faucet/port.py, faucet/stack.py, faucet/valve.py, faucet/valve_lldp.py, faucet/valve_route.py, faucet/valve_stack.py, faucet/valve_switch.py, faucet/valve_switch_stack.py, faucet/valve_switch_standalone.py, faucet/valve_util.py, faucet/valves_manager.py, tests/unit/faucet/test_config.py, tests/unit/faucet/test_valve_stack.py
`Stack`: All stack related DP methods are moved to a stack class `Stack` in `stack.py`. `Stack` provides the additional configuration option `down_time_multiple` that configures how many `FAUCET_STACK_ROOT_STATE_UPDATE_TIME` intervals for a down stack node to still be considered healthy.
`ValveStackManager`: All stack based algorithms in the various valve managers that don't directly belong in that valve manager have been moved to `ValveStackManager` in `valve_stack.py`. Part of the root nomination process has been moved to this class, along with the away & towards root port selection & pruning calculations. Tunnel updating has been moved to here as well.
`FAUCET_STACK_ROOT_STATE_UPDATE_TIME` environment variable configures the number of seconds to wait before checking stack root health. …
=> Refactor stacking into ValveStackManager & Stack classes

faucet/dp.py, tests/integration/mininet_tests.py
The fix tries to address a corner case which was discovered during operations with forchestrator/faucetizer where adding an empty acls_in results in an exception when calling dp.cold_start_port:
File "/usr/lib/python3/dist-packages/faucet/valve_util.py", line 34, in __koe
func(*args, **kwargs)
File "/usr/lib/python3/dist-packages/faucet/faucet.py", line 166, in reload_config
self.valves_manager.request_reload_configs(
File "/usr/lib/python3/dist-packages/faucet/valves_manager.py", line 289, in request_reload_configs
result = self.load_configs(now, new_config_file, delete_dp=delete_dp)
File "/usr/lib/python3/dist-packages/faucet/valves_manager.py", line 271, in load_configs
return self._apply_configs(self.parse_configs(new_config_file), now, delete_dp)
File …
=> Check for empty values when evaluating ACL changes in config.

.github/workflows/tests-codecheck.yml, .github/workflows/tests-integration.yml, .github/workflows/tests-unit.yml, clib/mininet_test_base.py, clib/mininet_test_base_topo.py, clib/mininet_test_topo.py, tests/integration/mininet_tests.py
Modify `NUM_FAUCET_CONTROLLER` constant to set how many controllers you want to run in the integration test suite.
Modify `FAUCET_CONTROLLER_START_DELAY` to change how long to wait before starting the next controller.
As expected group mod & meter mod tests fail due to incorrect order of group/meter flowmods. This is mostly fixed by having the `FAUCET_CONTROLLER_START_DELAY` which prevents the flowmod collision during startup, however when the tests flap the ports they will still encounter the problem.
8021X failures:
Pretty much all of the 8021X tests fail with 2 Faucet controllers running.
- Faucet8021XCustomACLLoginTest
- Faucet8021XCustomACLLogoutTest
- Faucet8021XDynACLLoginTest
- Faucet8021XDynACLLogoutTest
- Faucet8021XFailureTest
- Faucet8021XPortFlapTest
- …
=> Add multiple controllers to test redundancy for the integration tests

faucet/valve.py, tests/integration/mininet_tests.py
Forch relies on varz and events to maintain a cache of learned MAC entries. The PR makes sure that the respective varz are flushed and events triggered when the VLAN caches are flushed on config change.
=> Flush varz and trigger expire event when vlan host caches get cleared

clib/mininet_test_base_topo.py, clib/mininet_test_topo.py, docker/runtests.sh, tests/integration/mininet_multidp_tests.py
I can't seem to find the proper place to install the prerequisite dnsmasq, so it is haphazardly located in docker/runtests.sh.
=> Add DHCP tests to the integration test suite

clib/valve_test_lib.py, tests/unit/faucet/test_valve_stack.py
No specific problem observed, but it's the theory of the thing.
=> Don't use time.time in unit tests

.github/workflows/tests-integration.yml, Dockerfile.fuzz-config, Dockerfile.fuzz-packet, docker/runtests.sh
We shouldn't install apt packages in docker/runtests.sh as it slows the tests down and requires the test container have network connectivity to an apt mirror.
Revert change that was part of #3697 and install dnsmasq in the test-base image instead.
=> Apt packages shouldn't be installed in docker/runtests.sh.

clib/mininet_test_base.py, clib/valve_test_lib.py, faucet/dp.py, faucet/valve.py, faucet/valve_pipeline.py, faucet/valve_switch.py, faucet/valve_switch_stack.py, faucet/valve_switch_standalone.py, tests/integration/mininet_multidp_tests.py, tests/integration/mininet_tests.py, tests/unit/faucet/test_valve_config.py, tests/unit/faucet/test_valve_stack.py
* Remove use of table wildcard delete, which is impactful on forwarding and unnecessary.
* Enforce non-use of table wildcard deletes in the future.
* Move maintenance of VLAN antispoofing rules to switch managers, which have the necessary internal knowledge.
=> Simplify and make warm starting less impactful, by removing use of table wildcard deletes.

clib/config_generator.py, clib/mininet_test_base.py, clib/mininet_test_base_topo.py, docs/configuration.rst, faucet/dp.py, faucet/stack.py, faucet/valve.py, faucet/valve_lldp.py, faucet/valve_stack.py, faucet/valves_manager.py, tests/generative/unit/test_topology.py, tests/integration/mininet_multidp_tests.py, tests/unit/clib/test_topo.py, tests/unit/faucet/test_valve_stack.py
`min_stack_health` & `min_lacp_health` are just additional configuration options for deciding if a stack node is healthy.
We now keep track of the individual health percentages so deciding the best root candidate is easier. We choose a root by sorting a list of tuples taking favour of healthy nodes, followed by the highest health percentages, lastly followed by the priority.
=> Change root health & nomination calculation

faucet/acl.py, faucet/dp.py, faucet/valve.py, faucet/valve_acl.py, faucet/valve_of.py, faucet/valve_route.py, tests/integration/mininet_tests.py, tests/unit/faucet/test_valve.py
Incremental fixes while auditing table manager change methods.
* valve_route did not delete deconfigured VLAN
* Move meter add/change/del functions should move to ACL manager, and don't configure unused meters.
* ACL manager will call serialize() on same flows when parsing ACL, even if ACL doesn't change. Serialization check can be cached so that parse serialize() cost only needs to be paid once. Particularly impactful for very large, mostly static ACLs. Also test XID needs to be > 0 to avoid Ryu debug message when meters are used.
=> ACL warm start refactoring and performance improvements, and add missing del_vlan call to valve_route.

clib/config_generator.py, clib/fakeoftable.py, clib/mininet_test_base.py, clib/mininet_test_base_topo.py, clib/mininet_test_topo.py, clib/valve_test_lib.py, docs/configuration.rst, faucet/acl.py, faucet/conf.py, faucet/dp.py, faucet/valve.py, faucet/valve_acl.py, faucet/valve_of.py, faucet/valve_stack.py, tests/integration/mininet_multidp_tests.py, tests/unit/faucet/test_config.py, tests/unit/faucet/test_valve_stack.py
- Adds additional configuration options to the tunnel mechanism.
- Adds more DHCP tests to the integration test suite using the bidirectional tunnel to a coprocessor port with a dnsmasq server.
Allows for a tunnel ACL to be configured as a DP ACL as either a source (via `dp_acls`) or destination (by not specifying the tunnel option `port`). This will mean, once the packet has reached the destination DP, it will pop off the tunnel ID and then goto the `eth_dst` table.
`exit_instructions`: An additional list of output actions to apply to the packet after decapsulating from the tunnel and before outputting to the destination.
E.g. The following applies the VID 101 onto the packet after popping off the tunnel ID. This only applies to the forward direction of the tunnel if bidirectionality is …
=> Reverse tunnel

faucet/config_parser_util.py
Previously we read the config file and parsed it, then read it again to calculate the hash.
If the file changed between parsing it and calculating the hash, we would effectively miss the config change.
=> Fix race condition between reading a config file, and calculating its hash

README.rst
Waikato appears to have switched from mailman to postorius at some point, bringing a new URL format. The old URLs both redirect to the same uni-wide directory of mailing lists, which isn't super useful.
Thanks :)
=> README: update mailing list URLs

.github/workflows/tests-unit.yml
I broke codecov uploads when I refactored our github action runs into separate workflows (89008526fcec1aaeec98e5ba679bc333813d83a7).
Fix codecov uploads so they work again.
=> Fix codecov upload at end of unit test run.

faucet/faucet_metrics.py, faucet/valve.py, faucet/valve_lldp.py, faucet/valves_manager.py, tests/unit/faucet/test_valve.py, tests/unit/faucet/test_valve_stack.py
Adds varz to enable monitoring frequent changes to stack state, lacp status and stack root.
=> Add varz to track changes to stack state, lacp status and stack root

.github/workflows/tests-integration.yml, Dockerfile.fuzz-config, Dockerfile.fuzz-packet, Dockerfile.tests, clib/clib_mininet_test_main.py, docker/runtests.sh
* Changes test-base image to Debian from Ubuntu as Ubuntu have stopped supporting i386.
* Includes workaround for unknown psmisc version issue in debian buster (which is fixed in newer debian/ubuntu releases).
* Upgrade:
* openvswitch to v2.15.0.
* mininet to v2.3.0.
* Debian to buster.
needs new https://github.com/faucetsdn/docker-test-base release cut before this can be merged
=> Upgrade test-base image.

faucet/valve.py
When new ports are dynamically added to the configuration,
ensure that the dataplane is modified for ports that are
link up.
Ports that are not present in the dataplane, or currently
link down, will continue to be handled on link status changes
events.
=> valve.py: Only add up ports on config changes (#3865)

.dockerignore
* Our release process requires the .git directory to exist for docker
image builds to succeed.
=> Don't exclude .git directory from docker containers.

.github/workflows/release-debian.yml, .github/workflows/release-docker.yml, .github/workflows/release-python.yml
Prevent our release CIs from running if our tag format isn't used.
=> Only run release CIs if tag format is correct.

test-requirements.txt, tests/integration/mininet_tests.py
In order to avoid this exception with 'send(fuzz(...))' usage:
---
File "/venv/lib/python3.7/site-packages/scapy/arch/linux.py", line 605, in send
self.outs.bind(sdto)
TypeError: argument 1 must be str, not NetworkInterface
---
Which is seen in the following integration tests:
* FaucetUntaggedIPv4ControlPlaneFuzzTest
* FaucetUntaggedIPv6ControlPlaneFuzzTest
=> DownRev Scapy to 2.4.4 (#3869)

clib/mininet_test_base.py
For the multi-controller tests, the hard 'sleep()'s
are there to allow the host to process changes and
become idle once more.  Instead of hard 'sleep()'s,
wait for the host to become idle once more.
This improves the speed at which tests make
progress, and improves the overall integration
test suite execute time.
=> clib: speed up integration test execution

adapters/vendors/rabbitmq/rabbit.py, clib/clib_mininet_test_main.py, clib/fakeoftable.py, clib/mininet_test_base.py, clib/mininet_test_topo.py, clib/valve_test_lib.py, faucet/acl.py, faucet/dp.py, faucet/faucet.py, faucet/stack.py, faucet/valve.py, faucet/valve_lldp.py, faucet/valve_of.py, faucet/valve_packet.py, faucet/valve_route.py, faucet/valve_switch_stack.py, faucet/valve_switch_standalone.py, faucet/valve_util.py, faucet/vlan.py, tests/generative/fuzzer/config/generate_dict.py, tests/generative/integration/fault_tolerance_main.py, tests/unit/faucet/test_valve.py, tests/unit/faucet/test_valve_stack.py
The end of the pep8 automated changes (move tailing arithmetic / logic to the next line)
=> CodeCheck - Part2d

.pylintrc, faucet/config_parser.py, faucet/dp.py, faucet/stack.py, faucet/tfm_pipeline.py, faucet/valve_switch.py, faucet/watcher_conf.py, tests/integration/mininet_multidp_tests.py, tests/integration/mininet_tests.py, tests/unit/faucet/test_valve.py, tests/unit/faucet/test_valve_config.py, tests/unit/faucet/test_valve_egress.py, tests/unit/faucet/test_valve_stack.py
The initial pylint clean-ups : relating to white-listing startUp / teadDown / dp names
=> CodeCheck - Part4

tests/integration/mininet_tests.py
Now that Chewie is at 0.0.22, the requisite fix as documented
in [1] is now in place, so all the 'unexpected successes' should`
be treated as real successes once more, so any future failures
are correctly captured.
[1] 3c58caf13b6f581196f13d59a3ebe1016de4f6d0
=> tests: 802.1X successes should be real real successes

tests/integration/mininet_tests.py
Currently there is a delay in the startup of multiple Faucet controllers
that is causing this test to fail as a result of unsynchronized state.
For now, limit this test to a single Faucet instance.
=> Use a single Facuet instance for FaucetUntaggedMaxHostsTest (#3925)

clib/mininet_test_base.py, tests/integration/mininet_tests.py
* the `old pre_start_net` is now called `post_start_net` as this is where it really is called
* a new `pre_start_net` is re-introduced at the appropriate place
=> pre_start_net() updates

clib/mininet_test_base.py, tests/integration/mininet_tests.py
* Ensure individual controllers start the first time, but using unique resources were required
* Change the setup sequencing to ensure all controllers are running at the time the network is started
=> Better co-ordination of multiple controllers

clib/clib_mininet_test_main.py
Fix osken-manager version check which prevents docker test suite from starting up.
=> Fix osken-manager version check.

.readthedocs.yml
Fixes failing builds after #4003
=> Use python 3.8 for building our docs on readthedocs.

.github/workflows/tests-integration.yml, Dockerfile.fuzz-config, Dockerfile.fuzz-packet, Dockerfile.tests, clib/clib_mininet_test_main.py, tests/integration/mininet_tests.py
Upgrade to test-base v10.0.0 docker image which upgrades to Debian Bullseye and Open vSwitch 2.16.2.
This should fix our current failures running the test suite.
closes #4004
=> Upgrade to test-base v10.0.0.

docs/configuration.rst, faucet/acl.py, faucet/valve_acl.py, faucet/valve_of.py, faucet/valve_table.py, tests/integration/mininet_tests.py
Adds support for nicira extension conntrack matches and actions in faucet ACLs.
Throwing draft PR up for feedback, I've still got to write the documentation for this change.
=> Add support for using openvswitch conntrack in faucet ACLs

Dockerfile.faucet, adapters/vendors/faucetagent/Dockerfile, adapters/vendors/rabbitmq/Dockerfile
* Change base image from faucet/base to python:3.9-alpine3.15 to reduce size of faucet docker images.
=> Upgrade to faucet/python3 v8.0.0 base image.

docker/install-faucet.sh
Further reduce our docker image size by about 4MB.
* Add --no-cache flag to apk.
* Pip --no-cache-dir doesn't always work so manually clear the cache ourselves
=> Further reduce size of our docker image

README.rst, docs/developer_guide.rst, tests/integration/mininet_tests.py
While trying to follow the developer guidelines I was tricked into setting up a Travis CI account :)
=> Remove dated references to Travis

docs/tutorials/conntrack.rst, docs/tutorials/index.rst
This is an attempt at introducing a connection tracking tutorial with stateful ACL rules and sNAT examples. Initially discussed in issue #4104 and via email with @gizmoguy.
The first two sections (stateful fw rules and sNAT) are complete, but the intended ICMPv6/ARP filtering section is still a TODO. I ran out of time for the time being, so I'm looking for some feedback on the tutorial thus far.
Thanks!
=> Add a Connection Tracking Tutorial

docs/installation.rst, docs/tutorials/first_time.rst
* Use signed-by which enhances security of apt when third party repos are used
* Remove reference to wand OVS repo now that modern linux distros ship new versions of OVS with good openflow support
=> Update apt instructions used in documentation

docs/installation.rst, docs/tutorials/first_time.rst
The default keyring directory for third party repos has been changed to `/etc/apt/keyrings/`[1]
[1] https://wiki.debian.org/DebianRepository/UseThirdParty#OpenPGP_Key_distribution
=> Change apt keyring directory to /etc/apt/keyrings/.

docker/install-faucet.sh
os-ken now lists ncclient as a dependency (see #4145) which causes installation times and disk usage to increase beyond our acceptable limits.
Install our own fake ncclient in the docker build process which will prevent the real ncclient from being installed.
=> Skip installing ncclient in docker image.

.github/workflows/tests-integration.yml
Dependabot doesn't currently have the ability to update container image versions inside a github action workflow.
So instead of keeping it up to date, always use the latest version of the test-base to run integration tests.
=> Use latest version of test-base in github action workflow.

docs/_static/grafana-dashboards/faucet_instrumentation.json, docs/_static/grafana-dashboards/faucet_inventory.json, docs/_static/grafana-dashboards/faucet_port_statistics.json, etc/prometheus/faucet.rules.yml
I discovered that the Grafana Dashboards offered in the docs no longer work with later versions of Grafana. Specifically 9.x in my case. For whatever reason, Grafana does not migrate them correctly. Importing the old dashboards works, but editing the panels results in an exception in the Grafana frontend.
I tried importing the dashboards in each of the latest major Grafana versions since 5.x (6->7->8->9). It seemed to attempt to migrate the dashboards, but most of the panels were still broken.
I believe to have narrowed this down to a few different problems that had to be tweaked manually.
1. The "table" and "graph" panel visualizations were deprecated in favor of a newer "table" panel, and the "timeseries" graphs. 
2. The variable regex syntax changed in the query `expr` format.
This PR …
=> Update Grafana Dashboards to work with newer versions

.github/renovate.json, .github/workflows/tests-integration.yml
For docker-compose and github action docker tags only.
=> Partially re-enable renovatebot.

test-requirements.txt
tinyrpc v1.1.6 has started installing a global package named "tests":
https://github.com/mbr/tinyrpc/commit/07e17a05081f4a1afd365654f00f0a42a513bff9 
This is shadowing the faucet unit tests which are in the `tests` directory. Pin tinyrpc to an older version to make our tests run again.
=> Fix unit tests by not installing tinyrpc v1.1.6.

.github/workflows/tests-codecheck.yml
Error:
```
Running black on 
Usage: black [OPTIONS] SRC ...
One of 'SRC' or 'code' is required.
Error: Process completed with exit code 1.
```
=> Fix black tests not running when there have been no changed py files.

.github/workflows/periodic.yml
Exception: errFail: ('cgget -n -g cpu -g cpuacct -g cpuset /',) failed with return code 81: cgget: libcgroup initialization failed: Cgroup is not mounted
=> periodic tests failing under ubuntu-latest:

docker/install-faucet.sh, requirements.txt, tests/unit/packaging/test_packaging.py
ncclient as a dependency causes us some issues and since we don't make use of it skip installing it by installing our fakencclient package instead
=> Install fakencclient for all python package installs.

requirements.txt, tests/unit/packaging/test_packaging.py
Removing the "package name @" will prevent these override dependencies ending up in our python packaging metadata which should make faucet installable via pip again without this error:
ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
faucet depends on eventlet@ https://github.com/faucetsdn/eventlet/archive/main.tar.gz 
However, will remove python 3.12 support when installing faucet via pypi, i.e: "pip install faucet".
=> Prevent override deps from becoming part of python package.

docs/configuration.rst
Added documentation about the default listening port (6653) for Faucet and how it can be customized in configuration files such as /etc/default/faucet, /etc/default/gauge, and /etc/faucet/ryu.conf. 
This information helps users easily adapt Faucet's port settings to their specific network requirements.
Feel free to further adapt this is just a suggestion. But at least for me this information would have been quite useful.
I did not know that I also have to adapt /etc/default/gauge that's why I ran into some issues
PS: Nice tool thanks a lot for the good work
=> Add Default Port Hint

Dockerfile.fuzz-config, Dockerfile.fuzz-packet, Dockerfile.tests, clib/mininet_test_base.py, docker/runtests.sh, faucet/valve.py, faucet/valve_of.py, faucet/valve_packet.py, faucet/valve_route.py, faucet/valve_switch_standalone.py, tests/integration/mininet_tests.py
This patch allows faucet to reply to traceroute probes from hosts.
This changes faucet to request the openflow agent to send us packet ins of type `OFPR_INVALID_TTL` and adds to PacketMeta the reason a packet in was received (so we can disable learning from ` OFPR_INVALID_TTL` packets).
This patch slightly modifies the order of openflow actions in the FIB tables, to do `dec_ttl` before the `set_fields` that updates the src/dst mac addresses so that we can create the correct ICMP TTL expired response and send it to the right host.
=> Add support for sending ICMP v4 and v6 time exceeded messages.

docker-compose.yaml
=> Fix docker compose error: services.gauge.links must be a list
